#!/usr/bin/env bash
# resync-installed.sh - Refresh installed Loom surfaces from the recorded source (#3777, #4239).
#
# The installed Loom surfaces the harness actually executes/reads are copied from
# the Loom source repo's defaults/ tree at install time. After a `git pull` that
# merges a fix to those files, the INSTALLED copies are NOT automatically updated
# — so a repo can run stale hooks/scripts/roles/docs/commands indefinitely (see
# #3777: the guard-precision trio #3755/#3756/#3757 merged to main, but the
# installed guard-destructive.sh kept its pre-fix behavior until hand-copied).
#
# This is the REMEDIATION half of the drift problem. #3770
# (check-main-freshness.sh) DETECTS the drift with a warning; this script FIXES
# it. The intended flow is: "freshness warning says you're stale -> run resync."
#
# It is idempotent (a no-op when already in sync), reports per-file
# updated/created/unchanged/skipped, only ever touches files that exist in the
# source tree (repo-specific files with no source counterpart are left alone),
# never clobbers a symlinked install target, and supports --dry-run.
#
# Surfaces resynced (#4239 widened this from hooks+scripts to the full pure-copy
# surface map — note the asymmetric source->target mapping):
#   .loom/hooks/            <- defaults/hooks/            (top-level *.sh)
#   .loom/scripts/          <- defaults/scripts/          (recursive)
#   .loom/roles/            <- defaults/roles/            (recursive)
#   .loom/docs/             <- defaults/docs/             (recursive; symlinks skipped)
#   .loom/bin/              <- defaults/.loom/bin/        (recursive; live consumer CLI)
#   .claude/commands/loom/  <- defaults/.claude/commands/loom/ (recursive)
#
# On a successful non-dry-run it also re-stamps loom_version, loom_commit, and a
# last_resync date into .loom/install-metadata.json (requires jq or python3;
# skipped with a warning if neither is present — the file sync still succeeds).
#
# EXPLICITLY OUT OF SCOPE (never touched by resync — updated by other mechanisms):
#   .loom/config.json       - operator-owned; needs merge-semantics design
#   CLAUDE.md               - repo-customized at install; needs managed-section markers
#   .github/labels.yml,     - covered by `gh label sync` + install-time workflow opt-ins
#     .github/workflows/*
#   loom-daemon binary      - owned by the #4055 self-update mechanism
#   .mcp.json               - regenerated by scripts/setup-mcp.sh
#   install-metadata.json's install_date + installed_files - owned by the installer
#
# Local-override convention: list a relative path (e.g. `hooks/guard-destructive.sh`,
# `scripts/foo.sh`, `roles/custom-role.md`, `docs/notes.md`, `bin/loom`, or
# `commands/loom/mine.md`) — one per line — in `.loom/resync-ignore` to pin an
# intentional per-repo customization. Matching files are reported as `skipped`
# and never overwritten. Blank lines and `#` comments are ignored.
#
# Usage:
#   ./.loom/scripts/resync-installed.sh            # sync; report what changed
#   ./.loom/scripts/resync-installed.sh --dry-run  # preview only; make no changes
#   ./.loom/scripts/resync-installed.sh --quiet    # only report updated/skipped
#   ./.loom/scripts/resync-installed.sh --help     # show usage
#
# Exit codes:
#   0 - Success. Sync applied (or already in sync); or --dry-run found no drift.
#   1 - Error (not in a git repo, or the source tree could not be located).
#   2 - --dry-run only: drift detected (one or more files WOULD be updated).
#       Lets callers (e.g. the #3770 warning) use --dry-run as a cheap check.
#
# See also: check-main-freshness.sh (#3770) — the advisory that suggests this.

set -uo pipefail

# ---------- output helpers ----------

if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    BOLD='\033[1m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    BOLD=''
    NC=''
fi

DRY_RUN=0
QUIET=0

err()  { printf '%b\n' "${RED}ERROR: $*${NC}" >&2; }
warn() { printf '%b\n' "${YELLOW}WARN: $*${NC}" >&2; }
info() { printf '%b\n' "${BLUE}$*${NC}"; }
note() { [[ "$QUIET" -eq 1 ]] || printf '%b\n' "$*"; }

# ---------- args ----------

for arg in "$@"; do
    case "$arg" in
        --dry-run|-n) DRY_RUN=1 ;;
        --quiet|-q)   QUIET=1 ;;
        --help|-h)
            sed -n '2,61p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            err "Unknown argument: $arg (try --help)"
            exit 1
            ;;
    esac
done

# ---------- resolve the installed repo root (worktree-safe) ----------

if ! git rev-parse --git-dir >/dev/null 2>&1; then
    err "Not inside a git repository."
    exit 1
fi

# git-common-dir points at the MAIN checkout's .git even from a linked worktree,
# so installed .loom/ is always resolved against the primary worktree — never a
# transient issue worktree.
REPO_ROOT=""
COMMON_DIR="$(git rev-parse --git-common-dir 2>/dev/null || true)"
if [[ -n "$COMMON_DIR" ]]; then
    case "$COMMON_DIR" in
        */.git) REPO_ROOT="${COMMON_DIR%/.git}" ;;
    esac
fi
if [[ -z "$REPO_ROOT" ]]; then
    REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
fi
if [[ -z "$REPO_ROOT" || ! -d "$REPO_ROOT/.loom" ]]; then
    err "Could not resolve the installed repo root (no .loom/ found)."
    exit 1
fi

# ---------- resolve the defaults/ source tree ----------
#
# Mirrors lib/loom-tools.sh find_loom_tools() resolution order:
#   1. Loom source repo (dogfood): $REPO_ROOT/defaults/
#   2. Recorded loom-source-path (target repo install)
#   3. install-metadata.json "loom_source"
#
# SOURCE_ROOT is the parent of DEFAULTS_DIR (always <root>/defaults) and is used
# to read the current loom_version (package.json) + loom_commit (git HEAD) for
# the metadata re-stamp.

DEFAULTS_DIR=""
SOURCE_ROOT=""
resolve_defaults() {
    if [[ -d "$REPO_ROOT/defaults/hooks" || -d "$REPO_ROOT/defaults/scripts" ]]; then
        DEFAULTS_DIR="$REPO_ROOT/defaults"
        return 0
    fi
    if [[ -f "$REPO_ROOT/.loom/loom-source-path" ]]; then
        local src
        src="$(cat "$REPO_ROOT/.loom/loom-source-path" 2>/dev/null || true)"
        if [[ -n "$src" && -d "$src/defaults" ]]; then
            DEFAULTS_DIR="$src/defaults"
            return 0
        fi
    fi
    if [[ -f "$REPO_ROOT/.loom/install-metadata.json" ]]; then
        local src
        src="$(sed -n 's/.*"loom_source" *: *"\(.*\)".*/\1/p' "$REPO_ROOT/.loom/install-metadata.json" 2>/dev/null | head -1)"
        if [[ -n "$src" && -d "$src/defaults" ]]; then
            DEFAULTS_DIR="$src/defaults"
            return 0
        fi
    fi
    return 1
}

if ! resolve_defaults; then
    err "Could not locate a defaults/ source tree to sync from."
    err "Looked in: \$REPO_ROOT/defaults, .loom/loom-source-path, .loom/install-metadata.json."
    err "Re-run the Loom installer, or set .loom/loom-source-path to the Loom source repo."
    exit 1
fi
SOURCE_ROOT="$(dirname "$DEFAULTS_DIR")"

INSTALLED_HOOKS="$REPO_ROOT/.loom/hooks"
INSTALLED_SCRIPTS="$REPO_ROOT/.loom/scripts"

# ---------- local-override ignore list ----------

IGNORE_FILE="$REPO_ROOT/.loom/resync-ignore"
is_ignored() {
    # $1 = relative path like "hooks/foo.sh", "roles/bar.md", "bin/loom", etc.
    [[ -f "$IGNORE_FILE" ]] || return 1
    local rel="$1" line
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"                       # strip trailing comment
        line="${line#"${line%%[![:space:]]*}"}"  # ltrim
        line="${line%"${line##*[![:space:]]}"}"   # rtrim
        [[ -z "$line" ]] && continue
        [[ "$line" == "$rel" ]] && return 0
    done < "$IGNORE_FILE"
    return 1
}

# ---------- Loom-internal ownership boundary (#3464) ----------
#
# defaults/.loom-internal.list names defaults-relative paths the installer MUST
# NOT copy into a consumer repo (e.g. Loom-internal /loom:* skills). Resync must
# honor the same boundary or it would resurrect an internal file into a consumer
# on the next run. Same declarative list + exact-match semantics manifest.sh and
# the Rust installer consume.
INTERNAL_LIST="$DEFAULTS_DIR/.loom-internal.list"
is_loom_internal() {
    # $1 = defaults-relative path like ".claude/commands/loom/imagine.md"
    [[ -f "$INTERNAL_LIST" ]] || return 1
    local rel="$1" line
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"
        line="${line#"${line%%[![:space:]]*}"}"
        line="${line%"${line##*[![:space:]]}"}"
        [[ -z "$line" ]] && continue
        [[ "$line" == "$rel" ]] && return 0
    done < "$INTERNAL_LIST"
    return 1
}

# ---------- counters ----------

N_UPDATED=0
N_UNCHANGED=0
N_SKIPPED=0

# ---------- per-file sync ----------
#
# sync_one <src_file> <dst_file> <rel_label>
#   Copies src -> dst when they differ (unless --dry-run), preserving the
#   installed file's executable bit expectation. Only files that exist in the
#   source tree ever reach this function, so repo-specific installed files with
#   no source counterpart are never touched.
sync_one() {
    local src="$1" dst="$2" rel="$3"

    if is_ignored "$rel"; then
        note "  ${YELLOW}skipped${NC}   $rel ${YELLOW}(pinned in .loom/resync-ignore)${NC}"
        N_SKIPPED=$((N_SKIPPED + 1))
        return 0
    fi

    # Never clobber a symlinked install target. In THIS dogfood repo the
    # .loom/docs/*.md entries are symlinks pointing back into defaults/;
    # overwriting them would corrupt the source of truth. Consumers get real
    # file copies, so this only ever short-circuits the dogfood case.
    if [[ -L "$dst" ]]; then
        note "  ${YELLOW}skipped${NC}   $rel ${YELLOW}(symlink -> $(readlink "$dst" 2>/dev/null))${NC}"
        N_SKIPPED=$((N_SKIPPED + 1))
        return 0
    fi

    if [[ -f "$dst" ]] && cmp -s "$src" "$dst" 2>/dev/null; then
        note "  ${GREEN}unchanged${NC} $rel"
        N_UNCHANGED=$((N_UNCHANGED + 1))
        return 0
    fi

    # src and dst differ (or dst is missing) — this is an update.
    N_UPDATED=$((N_UPDATED + 1))
    local verb_past="updated" verb_pres="update"
    if [[ ! -f "$dst" ]]; then
        verb_past="created"
        verb_pres="create"
    fi

    if [[ "$DRY_RUN" -eq 1 ]]; then
        printf '%b\n' "  ${BOLD}would ${verb_pres}${NC} $rel"
        return 0
    fi

    mkdir -p "$(dirname "$dst")"
    if cp "$src" "$dst" 2>/dev/null; then
        # Match the executable bit of the source (defaults/ scripts/hooks are +x).
        if [[ -x "$src" ]]; then
            chmod +x "$dst" 2>/dev/null || true
        fi
        printf '%b\n' "  ${GREEN}${verb_past}${NC}   $rel"
    else
        err "failed to copy $rel"
        return 1
    fi
}

# ---------- generic recursive surface resync (#4239) ----------
#
# resync_tree <src_dir> <dst_dir> <report_prefix> <defaults_prefix>
#   Recursively resyncs every file under src_dir into dst_dir.
#   - report_prefix   : prepended to the relative path for per-file reporting AND
#                       for .loom/resync-ignore matching (e.g. "roles", "docs",
#                       "bin", "commands/loom").
#   - defaults_prefix : defaults-relative prefix for the .loom-internal.list
#                       ownership-boundary check (e.g. "roles", "docs",
#                       ".claude/commands/loom", ".loom/bin").
#   A missing src_dir is a silent no-op. Existing sync_one semantics (ignore
#   list, symlink skip, idempotent copy, --dry-run) apply per file.
resync_tree() {
    local src_dir="$1" dst_dir="$2" report_prefix="$3" defaults_prefix="$4"
    [[ -d "$src_dir" ]] || return 0
    info "Resyncing ${dst_dir#"$REPO_ROOT/"}/ from ${src_dir#"$REPO_ROOT/"}/ ..."
    local src rel
    while IFS= read -r -d '' src; do
        rel="${src#"$src_dir/"}"
        # Honor the installer's Loom-internal skip boundary (#3464) so resync
        # never resurrects an internal file into a consumer repo.
        if is_loom_internal "$defaults_prefix/$rel"; then
            continue
        fi
        sync_one "$src" "$dst_dir/$rel" "$report_prefix/$rel"
    done < <(find "$src_dir" -type f -print0 2>/dev/null | sort -z)
}

# ---------- canonical Repo Skills guard detection (#4041) ----------
#
# When the canonical generic guard (with the rjwalters/repo#29 fix) is installed
# in this repo, Loom's vendored generic guard (guard-destructive-generic.sh) is
# intentionally NOT installed — the guard-destructive.sh dispatcher defers to the
# canonical guard at runtime. Resync must therefore neither resurrect the vendored
# copy nor leave a stale one behind. Same marker probe the dispatcher/installer
# use, so all three agree on which guard wins.
CANONICAL_GUARD_PRESENT=0
if [[ -r "$REPO_ROOT/.claude/skills/repo/hooks/guard-destructive.sh" ]] && \
   grep -q 'repo#29' "$REPO_ROOT/.claude/skills/repo/hooks/guard-destructive.sh" 2>/dev/null; then
    CANONICAL_GUARD_PRESENT=1
fi

# ---------- walk hooks (top-level *.sh, matching the installer) ----------

if [[ -d "$DEFAULTS_DIR/hooks" && -d "$INSTALLED_HOOKS" ]]; then
    info "Resyncing .loom/hooks/ from ${DEFAULTS_DIR#"$REPO_ROOT/"}/hooks/ ..."
    shopt -s nullglob
    for src in "$DEFAULTS_DIR/hooks/"*.sh; do
        name="$(basename "$src")"
        # The vendored generic guard is conditional on the canonical guard (#4041).
        if [[ "$name" == "guard-destructive-generic.sh" && "$CANONICAL_GUARD_PRESENT" -eq 1 ]]; then
            if [[ -f "$INSTALLED_HOOKS/$name" ]]; then
                if [[ "$DRY_RUN" -eq 1 ]]; then
                    printf '%b\n' "  ${BOLD}would remove${NC} hooks/$name ${YELLOW}(canonical Repo Skills guard present)${NC}"
                else
                    rm -f "$INSTALLED_HOOKS/$name" 2>/dev/null || true
                    printf '%b\n' "  ${GREEN}removed${NC}   hooks/$name ${YELLOW}(canonical Repo Skills guard present)${NC}"
                fi
            else
                note "  ${GREEN}unchanged${NC} hooks/$name ${YELLOW}(canonical Repo Skills guard present — not installed)${NC}"
            fi
            continue
        fi
        sync_one "$src" "$INSTALLED_HOOKS/$name" "hooks/$name"
    done
    shopt -u nullglob
fi

# ---------- walk scripts (recursive, matching the installer's verify walk) ----------

if [[ -d "$DEFAULTS_DIR/scripts" && -d "$INSTALLED_SCRIPTS" ]]; then
    info "Resyncing .loom/scripts/ from ${DEFAULTS_DIR#"$REPO_ROOT/"}/scripts/ ..."
    while IFS= read -r -d '' src; do
        rel="${src#"$DEFAULTS_DIR/scripts/"}"
        sync_one "$src" "$INSTALLED_SCRIPTS/$rel" "scripts/$rel"
    done < <(find "$DEFAULTS_DIR/scripts" -type f -print0 | sort -z)
fi

# ---------- walk the widened pure-copy surfaces (#4239) ----------
#
# Each only runs when both its source and its installed destination exist, so a
# consumer that never received a surface is not force-populated. Local-only files
# (custom roles, repo-specific skills) have no source counterpart and are left
# untouched — the same rule that protects repo-specific hooks/scripts.

if [[ -d "$REPO_ROOT/.loom/roles" ]]; then
    resync_tree "$DEFAULTS_DIR/roles" "$REPO_ROOT/.loom/roles" "roles" "roles"
fi
if [[ -d "$REPO_ROOT/.loom/docs" ]]; then
    resync_tree "$DEFAULTS_DIR/docs" "$REPO_ROOT/.loom/docs" "docs" "docs"
fi
if [[ -d "$REPO_ROOT/.loom/bin" ]]; then
    resync_tree "$DEFAULTS_DIR/.loom/bin" "$REPO_ROOT/.loom/bin" "bin" ".loom/bin"
fi
if [[ -d "$REPO_ROOT/.claude/commands/loom" ]]; then
    resync_tree "$DEFAULTS_DIR/.claude/commands/loom" "$REPO_ROOT/.claude/commands/loom" "commands/loom" ".claude/commands/loom"
fi

# ---------- re-stamp install-metadata.json (#4239, non-dry-run only) ----------
#
# Refresh loom_version + loom_commit (from the resolved source tree) and record a
# last_resync date. install_date and installed_files are left to the installer.
# jq or python3 is required for a safe in-place JSON edit; if neither is present
# we warn and skip — the surface sync above still succeeded.

read_source_version() {
    local pj="$SOURCE_ROOT/package.json" v
    [[ -f "$pj" ]] || { echo "unknown"; return 0; }
    v="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$pj" | head -1)"
    [[ -n "$v" ]] && echo "$v" || echo "unknown"
}

restamp_metadata() {
    local meta="$REPO_ROOT/.loom/install-metadata.json"
    [[ -f "$meta" ]] || return 0

    local version commit today tmp
    version="$(read_source_version)"
    commit="$(git -C "$SOURCE_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
    today="$(date +%Y-%m-%d)"
    tmp="${meta}.tmp.$$"

    if command -v jq >/dev/null 2>&1; then
        if jq --arg v "$version" --arg c "$commit" --arg r "$today" \
              '.loom_version=$v | .loom_commit=$c | .last_resync=$r' \
              "$meta" > "$tmp" 2>/dev/null && [[ -s "$tmp" ]]; then
            mv "$tmp" "$meta"
            note "  ${GREEN}re-stamped${NC} install-metadata.json (loom_version=$version, loom_commit=$commit, last_resync=$today)"
            return 0
        fi
        rm -f "$tmp"
    fi

    if command -v python3 >/dev/null 2>&1; then
        if META="$meta" VERSION="$version" COMMIT="$commit" TODAY="$today" \
           python3 - "$tmp" <<'PY' 2>/dev/null && [[ -s "$tmp" ]]; then
import json, os, sys
with open(os.environ["META"]) as f:
    data = json.load(f)
data["loom_version"] = os.environ["VERSION"]
data["loom_commit"] = os.environ["COMMIT"]
data["last_resync"] = os.environ["TODAY"]
with open(sys.argv[1], "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY
            mv "$tmp" "$meta"
            note "  ${GREEN}re-stamped${NC} install-metadata.json (loom_version=$version, loom_commit=$commit, last_resync=$today)"
            return 0
        fi
        rm -f "$tmp"
    fi

    warn "Skipped install-metadata.json re-stamp (need jq or python3). Surface sync still applied."
    return 0
}

if [[ "$DRY_RUN" -ne 1 ]]; then
    restamp_metadata
fi

# ---------- summary ----------

echo ""
if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ "$N_UPDATED" -gt 0 ]]; then
        printf '%b\n' "${YELLOW}${BOLD}[resync] DRY RUN: ${N_UPDATED} file(s) would be updated, ${N_UNCHANGED} unchanged, ${N_SKIPPED} skipped.${NC}"
        printf '%b\n' "${YELLOW}Run without --dry-run to apply.${NC}"
        exit 2
    fi
    printf '%b\n' "${GREEN}[resync] DRY RUN: already in sync (${N_UNCHANGED} unchanged, ${N_SKIPPED} skipped).${NC}"
    exit 0
fi

if [[ "$N_UPDATED" -gt 0 ]]; then
    printf '%b\n' "${GREEN}${BOLD}[resync] ${N_UPDATED} file(s) updated, ${N_UNCHANGED} unchanged, ${N_SKIPPED} skipped.${NC}"
else
    printf '%b\n' "${GREEN}[resync] Already in sync (${N_UNCHANGED} unchanged, ${N_SKIPPED} skipped).${NC}"
fi
exit 0
