//! Deterministic trailer injection for agent-created commits (#9027).
//!
//! # Mechanism
//!
//! A dispatched issue sweep's environment carries a git **environment-scoped**
//! config entry (`GIT_CONFIG_COUNT` / `GIT_CONFIG_KEY_n` / `GIT_CONFIG_VALUE_n`,
//! git ≥ 2.31) setting `core.hooksPath` to a loom-generated shim directory.
//! Every hook in it first **chains** to the hook the repository itself would
//! have run — the `core.hooksPath` from its config files (e.g. `worktree.sh`'s
//! `.githooks`, #3638) or `$GIT_COMMON_DIR/hooks` — and the `commit-msg` shim
//! then runs `loom-daemon provenance stamp-commit-msg`, which appends the three
//! trailers with `git interpret-trailers`.
//!
//! Why this shape:
//!
//! - **Scoped to agent commits exactly.** Only processes spawned by the sweep
//!   inherit the override; the operator's own shell, the primary clone's
//!   config and the target repo's files are never modified.
//! - **Never clobbers the repo's hooks.** Nothing is written to any repo
//!   config; the repo's hooks still run, first, with their exit status
//!   honoured. (Git's config-defined hooks, `hook.<name>.command`, would
//!   compose natively but need git ≥ 2.54, newer than fleet hosts run.)
//! - **Deterministic.** The model is never asked to add trailers; a commit
//!   made through any tool (Bash, a native tool, `git commit --amend`) passes
//!   through `commit-msg`. `--no-verify` skips it, as it skips every hook.
//! - **Cannot block a commit.** A stamping failure is reported on stderr and
//!   the commit proceeds unstamped.
//! - **Other env-scoped config passes through.** The shim's lookup of the
//!   repo's own hooks rebuilds the `GIT_CONFIG_*` entries without loom's
//!   `core.hooksPath` entry (matched by [`HOOKS_DIR_ENV`]) and keeps every
//!   other one — e.g. a container's `safe.directory`.
//!
//! **Inside a sweep, the effective `core.hooksPath` is the shim directory.**
//! Anything that means "what did the repo configure" must read the config
//! files (`git config --local --get core.hooksPath`), not the effective value.
//!
//! Known gaps (#9079): if the shim directory is deleted mid-sweep (e.g.
//! `rm -rf .loom/logs`), git runs no hooks at all for the rest of that sweep,
//! the repo's included; containerized sweeps (`spawn-claude.sh` forwards only
//! `LOOM_*`/`CLAUDE_*` into `docker run`) are left unarmed, not broken.
use std::ffi::OsStr;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use super::Trailers;

/// `<story>` for the `Loom-Story` trailer.
pub const STORY_ENV: &str = "LOOM_PROVENANCE_STORY";
/// `<32-hex>|unknown` for `Loom-Trace-Id`.
pub const TRACE_ENV: &str = "LOOM_PROVENANCE_TRACE_ID";
/// The dispatching daemon's `BUILD_STAMP`, for `Loom-Build`.
pub const BUILD_ENV: &str = "LOOM_PROVENANCE_BUILD";
/// Absolute path of the `loom-daemon` the `commit-msg` shim execs.
pub const BIN_ENV: &str = "LOOM_PROVENANCE_BIN";
/// The shim directory exactly as written into `GIT_CONFIG_VALUE_n`, so the
/// shim can drop loom's own entry and keep the rest.
pub const HOOKS_DIR_ENV: &str = "LOOM_PROVENANCE_HOOKS_DIR";
/// `0` turns trailer injection off for a dispatch.
pub const ENABLE_ENV: &str = "LOOM_PROVENANCE_TRAILERS";

/// Every client- and server-side hook git runs by name. `push-to-checkout`
/// and `proc-receive` are omitted on purpose: their mere presence changes
/// what git does, so a shim for them would not be a pass-through.
pub const HOOK_NAMES: [&str; 24] = [
    "applypatch-msg",
    "pre-applypatch",
    "post-applypatch",
    "pre-commit",
    "pre-merge-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-rebase",
    "post-checkout",
    "post-merge",
    "pre-push",
    "pre-receive",
    "update",
    "post-receive",
    "post-update",
    "reference-transaction",
    "pre-auto-gc",
    "post-rewrite",
    "sendemail-validate",
    "post-index-change",
    "p4-changelist",
    "p4-prepare-changelist",
    "p4-post-changelist",
];

const SHIM: &str = r#"#!/bin/sh
# Generated by loom-daemon (provenance hooks v1, #9027). Do not edit.
# Git reaches this directory only through the GIT_CONFIG_* core.hooksPath
# override a dispatched loom sweep carries. Each hook first runs the hook the
# repository itself configured (its exit status is honoured), so the override
# adds to the repo's hooks and never replaces them; commit-msg then appends
# the Loom provenance trailers.
hook=${0##*/}
self=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
# git as the repository sees it: every env-scoped config entry except loom's
# own core.hooksPath one, passed on as -c (the same command scope).
repo_git() {
    _argc=$# _i=0 _n=${GIT_CONFIG_COUNT:-0}
    case $_n in '' | *[!0-9]*) _n=0 ;; esac
    while [ "$_i" -lt "$_n" ]; do
        eval "_k=\${GIT_CONFIG_KEY_$_i-} _v=\${GIT_CONFIG_VALUE_$_i-}"
        if [ "$_k" != core.hooksPath ] || [ "$_v" != "${LOOM_PROVENANCE_HOOKS_DIR-}" ]; then
            set -- "$@" -c "$_k=$_v"
        fi
        _i=$((_i + 1))
    done
    while [ "$_argc" -gt 0 ]; do
        set -- "$@" "$1"
        shift
        _argc=$((_argc - 1))
    done
    env -u GIT_CONFIG_COUNT git "$@"
}
orig=$(repo_git config --type=path --get core.hooksPath 2>/dev/null)
[ -n "$orig" ] || orig="$(repo_git rev-parse --git-common-dir 2>/dev/null)/hooks"
target=$(CDPATH= cd -- "$orig" 2>/dev/null && pwd -P) || target=
if [ -n "$target" ] && [ "$target" != "$self" ] && [ -f "$target/$hook" ] && [ -x "$target/$hook" ]; then
    if [ "$hook" != commit-msg ]; then
        exec "$target/$hook" "$@"
    fi
    "$target/$hook" "$@" || exit $?
fi
if [ "$hook" = commit-msg ] && [ -n "${LOOM_PROVENANCE_BIN:-}" ]; then
    "$LOOM_PROVENANCE_BIN" provenance stamp-commit-msg "$1" \
        || echo "loom: provenance trailers were not stamped on this commit" >&2
fi
exit 0
"#;

/// Where a workspace's shims live (`.loom/logs/` is gitignored in every
/// Loom-installed repo).
#[must_use]
pub fn hooks_dir(root: &Path) -> PathBuf {
    let root = std::path::absolute(root).unwrap_or_else(|_| root.to_path_buf());
    root.join(".loom/logs/provenance-hooks/v1")
}

/// Write (or refresh) every shim in `dir`. Idempotent; rewrites only a shim
/// whose content or mode differs, via rename so a concurrent commit never
/// executes a half-written file.
pub fn ensure_hooks(dir: &Path) -> io::Result<()> {
    std::fs::create_dir_all(dir)?;
    for name in HOOK_NAMES {
        let path = dir.join(name);
        if std::fs::read(&path).is_ok_and(|b| b == SHIM.as_bytes()) && is_executable(&path) {
            continue;
        }
        static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        let seq = SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let tmp = dir.join(format!(".{name}.{}.{seq}.tmp", std::process::id()));
        std::fs::write(&tmp, SHIM)?;
        set_executable(&tmp)?;
        std::fs::rename(&tmp, &path)?;
    }
    Ok(())
}

#[cfg(unix)]
fn is_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    std::fs::metadata(path).is_ok_and(|m| m.permissions().mode() & 0o111 == 0o111)
}

#[cfg(not(unix))]
fn is_executable(_: &Path) -> bool {
    true
}

#[cfg(unix)]
fn set_executable(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))
}

#[cfg(not(unix))]
fn set_executable(_: &Path) -> io::Result<()> {
    Ok(())
}

/// Arm trailer injection on a dispatched sweep child for `issue`, with this
/// process's own binary as the stamper. A `None` issue (PR-set dispatch) has
/// no story, so it is left unstamped.
pub fn prepare_child(command: &mut Command, root: &Path, issue: Option<u32>) {
    let Ok(bin) = std::env::current_exe() else {
        log::warn!("provenance: cannot locate this binary; commits will not carry trailers");
        return;
    };
    prepare_child_with(command, root, issue, &live_path(bin));
}

/// On Linux, `current_exe()` of a binary replaced in place (self-update)
/// reads `<path> (deleted)`; the replacement lives at `<path>`, so stamp with
/// that rather than a path that no longer exists.
fn live_path(bin: PathBuf) -> PathBuf {
    let text = bin.to_string_lossy();
    match text.strip_suffix(" (deleted)") {
        Some(live) if !bin.exists() => PathBuf::from(live),
        _ => bin,
    }
}

/// [`prepare_child`] with the stamping binary named explicitly (tests).
pub fn prepare_child_with(command: &mut Command, root: &Path, issue: Option<u32>, bin: &Path) {
    for key in [STORY_ENV, TRACE_ENV, BUILD_ENV, BIN_ENV, HOOKS_DIR_ENV] {
        command.env_remove(key);
    }
    let Some(issue) = issue else { return };
    if std::env::var(ENABLE_ENV).is_ok_and(|v| v.trim() == "0") {
        return;
    }
    let dir = hooks_dir(root);
    if let Err(error) = ensure_hooks(&dir) {
        log::warn!(
            "provenance: cannot write commit hooks under {}: {error}; commits will not carry trailers",
            dir.display()
        );
        return;
    }
    let trailers = Trailers::for_issue(root, issue);
    command
        .env(STORY_ENV, &trailers.story)
        .env(TRACE_ENV, &trailers.trace_id)
        .env(BUILD_ENV, &trailers.build)
        .env(BIN_ENV, bin)
        .env(HOOKS_DIR_ENV, &dir);
    append_git_config_env(command, "core.hooksPath", dir.as_os_str());
}

/// Append one `GIT_CONFIG_KEY_n`/`GIT_CONFIG_VALUE_n` pair after any entries
/// the command (or, failing that, this process) already carries, so an
/// existing environment-scoped config is extended rather than replaced.
fn append_git_config_env(command: &mut Command, key: &str, value: &OsStr) {
    let explicit = command
        .get_envs()
        .find(|(k, _)| *k == "GIT_CONFIG_COUNT")
        .map(|(_, v)| v.map(|v| v.to_string_lossy().into_owned()));
    let current = match explicit {
        Some(value) => value,
        None => std::env::var("GIT_CONFIG_COUNT").ok(),
    };
    let n: usize = current.and_then(|v| v.trim().parse().ok()).unwrap_or(0);
    command
        .env(format!("GIT_CONFIG_KEY_{n}"), key)
        .env(format!("GIT_CONFIG_VALUE_{n}"), value)
        .env("GIT_CONFIG_COUNT", (n + 1).to_string());
}

/// The trailers a sweep's environment carries, or `None` outside one.
#[must_use]
pub fn trailers_from_env() -> Option<Trailers> {
    let story = std::env::var(STORY_ENV)
        .ok()
        .filter(|s| !s.trim().is_empty())?;
    let var = |key, fallback: &str| {
        std::env::var(key)
            .ok()
            .filter(|s: &String| !s.trim().is_empty())
            .unwrap_or_else(|| fallback.to_string())
    };
    let unknown = super::UNKNOWN;
    Some(Trailers {
        story,
        trace_id: var(TRACE_ENV, unknown),
        // `Loom-Build` keeps its three-part shape even when unknown.
        build: var(BUILD_ENV, &format!("{unknown} {unknown} {unknown}")),
    })
}

/// Append (or replace) the three trailers in the commit message at `path`.
/// Replacing keeps an amended commit at exactly one of each.
pub fn stamp_message_file(path: &Path, trailers: &Trailers) -> io::Result<()> {
    let mut cmd = Command::new("git");
    cmd.args(["interpret-trailers", "--in-place", "--if-exists", "replace"]);
    for line in trailers.lines() {
        cmd.arg("--trailer").arg(line);
    }
    let status = cmd.arg(path).status()?;
    if status.success() {
        Ok(())
    } else {
        Err(io::Error::other(format!("git interpret-trailers exited {status}")))
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn git_config_env_is_appended_not_replaced() {
        let mut cmd = Command::new("true");
        cmd.env("GIT_CONFIG_COUNT", "2");
        append_git_config_env(&mut cmd, "core.hooksPath", OsStr::new("/x"));
        let get = |k: &str| {
            cmd.get_envs()
                .find(|(key, _)| *key == k)
                .and_then(|(_, v)| v)
                .map(|v| v.to_string_lossy().into_owned())
        };
        assert_eq!(get("GIT_CONFIG_COUNT").as_deref(), Some("3"));
        assert_eq!(get("GIT_CONFIG_KEY_2").as_deref(), Some("core.hooksPath"));
        assert_eq!(get("GIT_CONFIG_VALUE_2").as_deref(), Some("/x"));
    }

    #[test]
    fn ensure_hooks_writes_every_shim_executable_and_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        ensure_hooks(dir.path()).unwrap();
        ensure_hooks(dir.path()).unwrap();
        let mut names: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().into_string().unwrap())
            .collect();
        names.sort();
        let mut expected: Vec<_> = HOOK_NAMES.iter().map(ToString::to_string).collect();
        expected.sort();
        assert_eq!(names, expected, "no temp files left behind");
        for name in HOOK_NAMES {
            assert!(is_executable(&dir.path().join(name)), "{name}");
        }
    }

    #[test]
    fn a_self_updated_binary_is_stamped_by_its_live_path() {
        let dir = tempfile::tempdir().unwrap();
        let live = dir.path().join("loom-daemon");
        std::fs::write(&live, "").unwrap();
        let deleted = PathBuf::from(format!("{} (deleted)", live.display()));
        assert_eq!(live_path(deleted), live);
        assert_eq!(live_path(live.clone()), live);
    }

    #[test]
    fn a_pr_set_dispatch_is_not_armed() {
        let dir = tempfile::tempdir().unwrap();
        let mut cmd = Command::new("true");
        cmd.env(STORY_ENV, "stale");
        prepare_child_with(&mut cmd, dir.path(), None, Path::new("/bin/true"));
        assert!(cmd.get_envs().any(|(k, v)| k == STORY_ENV && v.is_none()));
        assert!(!cmd.get_envs().any(|(k, _)| k == "GIT_CONFIG_COUNT"));
        assert!(!hooks_dir(dir.path()).exists());
    }
}
