//! Byte assertions on the generated Kimi bindings. These files are the
//! whole enforcement boundary for a guarded Kimi launch, so they are pinned
//! exactly rather than spot-checked: a silent widening (a builtin re-added
//! to `enabled`, a glob that matches a second server, a non-empty
//! `subagents`) has to fail here, not on a live host.
use super::*;
use std::path::PathBuf;

const SERVER: &str = "loom-0123456789abcdef";

#[test]
fn the_server_name_is_per_launch_and_kebab_case() {
    let one = server_name(Path::new("/state/loom/native-tools/hash/launch-a"));
    let two = server_name(Path::new("/state/loom/native-tools/hash/launch-b"));
    assert_ne!(one, two, "a second launch must not reuse the first one's name");
    assert_eq!(one, server_name(Path::new("/state/loom/native-tools/hash/launch-a")));
    assert!(one.starts_with("loom-"), "{one}");
    assert_eq!(one.len(), "loom-".len() + 16, "{one}");
    assert!(
        one.chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
        "{one}"
    );
    assert_eq!(tool_glob(&one), format!("mcp__{one}__*"));
}

#[test]
fn config_toml_is_generated_byte_for_byte() {
    assert_eq!(
        config_toml(SERVER, "'/bin/loom-daemon' native-mcp --pretooluse-guard"),
        concat!(
            "# Generated by Loom for one guarded launch. Do not edit; not the operator's config.\n",
            "default_permission_mode = \"auto\"\n",
            "\n",
            "# `enabled` is an allowlist. A builtin tool is active only if this list\n",
            "# contains its EXACT name; an MCP tool only if one of these globs matches.\n",
            "# So a binding that fails to load leaves no executable tool at all.\n",
            "[tools]\n",
            "enabled = [\"mcp__loom-0123456789abcdef__*\"]\n",
            "disabled = [\"Agent\", \"AgentSwarm\", \"Bash\", \"Edit\", \"Write\"]\n",
            "\n",
            "# Defense in depth ONLY: this hook surface is fail-open (a crashed,\n",
            "# timed-out or non-2 exit is treated as allow), so it is never the\n",
            "# boundary -- `[tools] enabled` above is.\n",
            "[[hooks]]\n",
            "event = \"PreToolUse\"\n",
            "command = \"'/bin/loom-daemon' native-mcp --pretooluse-guard\"\n",
            "timeout = 20\n",
        )
    );
}

#[test]
fn config_toml_never_admits_a_builtin_or_a_second_mcp_server() {
    let generated = config_toml(SERVER, "x");
    for builtin in [
        "Bash",
        "Write",
        "Edit",
        "Read",
        "Glob",
        "Grep",
        "Agent",
        "AgentSwarm",
    ] {
        assert!(
            !generated.contains(&format!("enabled = [\"{builtin}\"")),
            "{builtin} must never appear in the allowlist"
        );
    }
    // Exactly one allowlist entry, and it is this launch's own glob.
    assert!(generated.contains(&format!("enabled = [\"{}\"]\n", tool_glob(SERVER))));
    assert!(!generated.contains("mcp__*"), "a wildcard server glob would admit any server");
}

#[test]
fn mcp_json_is_generated_byte_for_byte_and_carries_no_credential() {
    let generated = mcp_json(
        SERVER,
        Path::new("/usr/local/bin/loom-daemon"),
        Path::new("/work/repo"),
        Path::new("/work/repo/.loom/worktrees/issue-1"),
        Path::new("/work/repo/.loom/hooks"),
    )
    .unwrap();
    assert_eq!(
        generated,
        concat!(
            "{\n",
            "  \"mcpServers\": {\n",
            "    \"loom-0123456789abcdef\": {\n",
            "      \"transport\": \"stdio\",\n",
            "      \"command\": \"/usr/local/bin/loom-daemon\",\n",
            "      \"args\": [\n",
            "        \"native-mcp\",\n",
            "        \"--workspace\",\n",
            "        \"/work/repo\",\n",
            "        \"--cwd\",\n",
            "        \"/work/repo/.loom/worktrees/issue-1\"\n",
            "      ],\n",
            "      \"cwd\": \"/work/repo/.loom/worktrees/issue-1\",\n",
            "      \"env\": {\n",
            "        \"LOOM_WORKSPACE\": \"/work/repo\",\n",
            "        \"LOOM_NATIVE_TOOL_BIN\": \"/usr/local/bin/loom-daemon\",\n",
            "        \"LOOM_NATIVE_GUARD_DIR\": \"/work/repo/.loom/hooks\"\n",
            "      }\n",
            "    }\n",
            "  }\n",
            "}\n",
        )
    );
    // The server's environment carries workspace context only: no key, no
    // token, no auth path. Credentials reach the CLI through the profile's
    // own env mapping, never through a file Loom writes.
    let parsed: serde_json::Value = serde_json::from_str(&generated).unwrap();
    let env = parsed["mcpServers"][SERVER]["env"].as_object().unwrap();
    let mut keys: Vec<&str> = env.keys().map(String::as_str).collect();
    keys.sort_unstable();
    assert_eq!(
        keys,
        [
            "LOOM_NATIVE_GUARD_DIR",
            "LOOM_NATIVE_TOOL_BIN",
            "LOOM_WORKSPACE"
        ]
    );
}

#[test]
fn the_agent_file_denies_delegation_and_every_unguarded_builtin() {
    let generated = agent_file(SERVER);
    assert!(generated.starts_with("---\nname: loom-worker\n"), "{generated}");
    assert!(generated.contains("\ndescription: Loom guarded issue worker\n"));
    assert!(generated.contains(&format!("\ntools:\n  - {}\n", tool_glob(SERVER))));
    for builtin in DISABLED_BUILTINS {
        assert!(generated.contains(&format!("\n  - {builtin}\n")), "{builtin}");
    }
    assert!(generated.contains("\nsubagents: []\n"), "delegation must be empty, not absent");
    // The parser rejects an agent file with an empty prompt body.
    let body = generated
        .split("\n---\n")
        .nth(1)
        .expect("a body after the frontmatter");
    assert!(!body.trim().is_empty());
}

#[test]
fn the_hook_command_shell_quotes_every_path() {
    let command = hook_command(
        Path::new("/opt/loom daemon/bin/loom-daemon"),
        Path::new("/work/it's a repo"),
        Path::new("/work/cwd"),
    )
    .unwrap();
    assert_eq!(
        command,
        concat!(
            "'/opt/loom daemon/bin/loom-daemon' native-mcp ",
            "--workspace '/work/it'\\''s a repo' --cwd '/work/cwd' --pretooluse-guard"
        )
    );
}

#[test]
fn non_utf8_paths_refuse_rather_than_generate_a_truncated_binding() {
    #[cfg(unix)]
    {
        use std::os::unix::ffi::OsStrExt;
        let bad = PathBuf::from(std::ffi::OsStr::from_bytes(b"/work/\xff"));
        assert!(mcp_json(SERVER, &bad, Path::new("/w"), Path::new("/w"), Path::new("/g")).is_err());
        assert!(hook_command(&bad, Path::new("/w"), Path::new("/w")).is_err());
    }
}
