//! Per-launch Kimi Code CLI bindings (#8562): the generated `config.toml`,
//! `mcp.json` and agent file that confine a guarded launch to the four
//! `loom_*` tools served by [`super::mcp`].
//!
//! Every shape here was read out of `@moonshot-ai/kimi-code` **2.0.2**'s own
//! bundle, not inferred from prose:
//!
//! | Surface | Bundle evidence |
//! | --- | --- |
//! | `KIMI_CODE_HOME` → `<home>/config.toml`, `<home>/mcp.json` | `resolveKimiHome` / `resolveConfigPath` |
//! | `mcp.json` is `{"mcpServers":{…}}`; stdio entry is `command`/`args`/`env`/`cwd` | `parseMcpJsonServers`, `McpServerStdioConfigSchema` |
//! | `[tools] enabled`/`disabled` | `ToolsConfigSchema`, `registerConfigSection("tools", …)` |
//! | builtin tools need an EXACT name match in `enabled`; MCP tools glob-match | `isToolActive`: `source !== "mcp" ? policy.tools.includes(name) : …isMatch(name, pattern)` |
//! | MCP tools are named `mcp__<server>__<tool>` | `MCP_NAME_PREFIX = "mcp__"` |
//! | agent file frontmatter `name`/`description`/`tools`/`disallowedTools`/`subagents` + non-empty body | the agent-file parser's `AgentFileParseError` paths |
//! | `[[hooks]]` is `{event, matcher?, command, timeout?}`, `.strict()` | `HookDefSchema`, `HOOK_EVENT_TYPES` |
//! | a hook that crashes/times out/exits non-2 ALLOWS the call | `allowResult` is the default return of the hook runner |
//!
//! **Why the server name carries a per-launch nonce.** Kimi resolves
//! `mcp.json` in three layers — `$KIMI_CODE_HOME/mcp.json` (ours),
//! `<gitWorkTreeRoot>/.mcp.json`, and `<cwd>/.kimi-code/mcp.json` — and a
//! later layer **overwrites a same-named entry from an earlier one**
//! (`loadMcpServersDetailed`). Both later layers live inside the worktree a
//! guarded worker may legitimately write to. A fixed server name would
//! therefore let repository content shadow the Loom server for the *next*
//! launch in that worktree. With a nonce, a stale/planted entry keeps the
//! old name, no longer matches this launch's `mcp__loom-<nonce>__*`
//! allowlist, and its tools are filtered out before the model sees them.
use anyhow::{Context, Result};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::path::Path;

/// Kimi 2.0.2's own builtin tool names that write, execute or delegate.
///
/// Listing them in `[tools] disabled` is belt-and-braces: `enabled` is
/// already an exact-match allowlist for builtins, so none of these is
/// reachable even if this list were empty or misspelled. It exists so a
/// future config regression that widens `enabled` still cannot re-expose
/// the unguarded write/execute/delegate surface silently.
const DISABLED_BUILTINS: &[&str] = &["Agent", "AgentSwarm", "Bash", "Edit", "Write"];

/// The MCP server name for one launch, derived from that launch's private
/// state directory so it is stable within a launch and distinct across
/// launches. Kebab-case (`AGENT_NAME_PATTERN`-safe and glob-safe).
pub fn server_name(launch_directory: &Path) -> String {
    let digest = Sha256::digest(launch_directory.as_os_str().as_encoded_bytes());
    format!("loom-{}", &hex::encode(digest)[..16])
}

/// The `mcp__<server>__*` glob that admits exactly this launch's guarded
/// tools and nothing else.
pub fn tool_glob(server: &str) -> String {
    format!("{}{server}__*", super::mcp::MCP_NAME_PREFIX)
}

fn toml_string(value: &str) -> String {
    // TOML basic strings and JSON strings share their escape syntax for
    // everything serde_json emits, so this is an exact, injection-free
    // encoding of an arbitrary path or command line.
    serde_json::Value::String(value.to_owned()).to_string()
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// The generated `config.toml`. Byte-for-byte deterministic given the same
/// inputs, so a test can assert it and `kimi doctor config` can validate it.
pub fn config_toml(server: &str, hook_command: &str) -> String {
    let disabled: Vec<String> = DISABLED_BUILTINS.iter().map(|t| toml_string(t)).collect();
    format!(
        "# Generated by Loom for one guarded launch. Do not edit; not the operator's config.\n\
         default_permission_mode = \"auto\"\n\
         \n\
         # `enabled` is an allowlist. A builtin tool is active only if this list\n\
         # contains its EXACT name; an MCP tool only if one of these globs matches.\n\
         # So a binding that fails to load leaves no executable tool at all.\n\
         [tools]\n\
         enabled = [{glob}]\n\
         disabled = [{disabled}]\n\
         \n\
         # Defense in depth ONLY: this hook surface is fail-open (a crashed,\n\
         # timed-out or non-2 exit is treated as allow), so it is never the\n\
         # boundary -- `[tools] enabled` above is.\n\
         [[hooks]]\n\
         event = \"PreToolUse\"\n\
         command = {hook}\n\
         timeout = 20\n",
        glob = toml_string(&tool_glob(server)),
        disabled = disabled.join(", "),
        hook = toml_string(hook_command),
    )
}

/// The generated `mcp.json`: exactly one stdio server, no credential value
/// in it or in the argv it names.
pub fn mcp_json(
    server: &str,
    binary: &Path,
    workspace: &Path,
    cwd: &Path,
    guard_directory: &Path,
) -> Result<String> {
    let path = |value: &Path| -> Result<String> {
        Ok(value
            .to_str()
            .with_context(|| format!("native path is not UTF-8: {}", value.display()))?
            .to_owned())
    };
    let (binary, workspace, cwd, guard) =
        (path(binary)?, path(workspace)?, path(cwd)?, path(guard_directory)?);
    let document = json!({"mcpServers":{server:{
        "transport":"stdio",
        "command":binary,
        "args":["native-mcp","--workspace",workspace,"--cwd",cwd],
        "cwd":cwd,
        "env":{
            "LOOM_WORKSPACE":workspace,
            "LOOM_NATIVE_TOOL_BIN":binary,
            "LOOM_NATIVE_GUARD_DIR":guard
        }
    }}});
    Ok(format!("{}\n", serde_json::to_string_pretty(&document)?))
}

/// The generated `--agent-file` definition: a primary agent whose tool
/// allowlist is this launch's MCP glob and whose subagent allowlist is
/// empty, so delegation cannot reintroduce an unguarded surface.
pub fn agent_file(server: &str) -> String {
    let disallowed: String = DISABLED_BUILTINS
        .iter()
        .map(|tool| format!("  - {tool}\n"))
        .collect();
    format!(
        "---\n\
         name: loom-worker\n\
         description: Loom guarded issue worker\n\
         tools:\n  \
           - {glob}\n\
         disallowedTools:\n{disallowed}\
         subagents: []\n\
         ---\n\
         \n\
         You are a Loom worker. Your only tools are `{glob}` — Loom's guarded\n\
         read, write, edit and shell tools. Every call is checked against Loom's\n\
         worktree, workflow and destructive-command policies before it runs, and\n\
         a refusal explains itself: read the reason and change course rather than\n\
         retrying the same call.\n\
         \n\
         There is no other tool surface and no delegation. If a task appears to\n\
         need one, say so plainly instead of working around it.\n\
         \n\
         Follow the role instructions in the prompt you were given.\n",
        glob = tool_glob(server),
        disallowed = disallowed,
    )
}

/// The hook command line written into `config.toml`. Shell-quoted, so a
/// space or quote in any path cannot split an argument.
pub fn hook_command(binary: &Path, workspace: &Path, cwd: &Path) -> Result<String> {
    let quote = |value: &Path| -> Result<String> {
        Ok(shell_quote(
            value
                .to_str()
                .with_context(|| format!("native path is not UTF-8: {}", value.display()))?,
        ))
    };
    Ok(format!(
        "{} native-mcp --workspace {} --cwd {} --pretooluse-guard",
        quote(binary)?,
        quote(workspace)?,
        quote(cwd)?
    ))
}

#[cfg(test)]
#[path = "kimi_tests.rs"]
mod tests;
