//! Corpus construction + oracle generation for [`super`]'s differential
//! suite, split out under `file-size-policy.md`'s 1000-code-line ratchet.
//!
//! Everything here builds the CASES (`build_corpus`) or regenerates the
//! frozen fixture from them (`regenerate_oracle`, ignored by default); the
//! comparison itself — running a case against both sides and classifying any
//! difference — stays in the parent module, reached here through explicit
//! `use super::{...}` imports.

use std::path::{Path, PathBuf};
use std::process::Command;

use super::{
    installed_name, load_oracle, repo_name, run_case, Case, Installed, Repo, ARGV0, FIXED_PATH,
    FIXED_TARGET,
};

struct Push<'a> {
    cases: &'a mut Vec<Case>,
}

impl Push<'_> {
    #[allow(clippy::too_many_arguments)]
    fn add(
        &mut self,
        id: String,
        argv: Vec<&str>,
        env: Vec<(&str, Option<&str>)>,
        installed: Installed,
        repo: Repo,
        flags_file: Option<&str>,
        stale_entry_points: Vec<&str>,
        running: bool,
    ) {
        self.cases.push(Case {
            id,
            argv: argv
                .into_iter()
                .map(std::string::ToString::to_string)
                .collect(),
            env: env
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.map(std::string::ToString::to_string)))
                .collect(),
            installed,
            repo,
            flags_file: flags_file.map(std::string::ToString::to_string),
            running,
            stale_entry_points: stale_entry_points
                .into_iter()
                .map(std::string::ToString::to_string)
                .collect(),
            self_located: false,
        });
    }

    /// A case that runs from outside any checkout and resolves the source tree
    /// through the entry point's own location — via a symlink. See
    /// [`Case::self_located`].
    fn add_self_located(
        &mut self,
        id: String,
        argv: Vec<&str>,
        env: Vec<(&str, Option<&str>)>,
        installed: Installed,
        repo: Repo,
    ) {
        self.add(id, argv, env, installed, repo, None, vec![], false);
        self.cases.last_mut().expect("just pushed").self_located = true;
    }
}

/// Build the corpus from the grammar the script parses, not from memory.
///
/// Deterministic and order-stable: the fixture is regenerated by replaying
/// this exact function, so a diff of the fixture is a diff of this function.
fn build_corpus() -> Vec<Case> {
    let mut cases = Vec::new();
    let mut p = Push { cases: &mut cases };

    // The two pure-inspection modes every behavioural group is run through.
    let modes = ["--check", "--dry-run"];

    // -----------------------------------------------------------------
    // A. Staleness detection × mode × --force × --allow-stale.
    //
    //    This is the decision the whole script exists to make, and it is the
    //    one place the installed binary's `--version` text meets the
    //    checkout's HEAD. `NoCommit` and `Absent` are in the grammar because
    //    `extract_commit` can legitimately yield "" — nothing in the retained
    //    suite's assertions says what happens then.
    // -----------------------------------------------------------------
    for mode in modes {
        for installed in [
            Installed::Current,
            Installed::Stale,
            Installed::NoCommit,
            Installed::Absent,
        ] {
            for force in [false, true] {
                for allow_stale in [false, true] {
                    let mut argv = vec![mode];
                    if force {
                        argv.push("--force");
                    }
                    if allow_stale {
                        argv.push("--allow-stale");
                    }
                    p.add(
                        format!(
                            "A/{mode}/{}/{}/{}",
                            installed_name(installed),
                            if force { "force" } else { "-" },
                            if allow_stale { "stale-ok" } else { "-" }
                        ),
                        argv,
                        vec![("LOOM_DAEMON_UPDATE_FETCH", Some("0"))],
                        installed,
                        Repo::Source,
                        None,
                        vec![],
                        false,
                    );
                }
            }
        }
    }

    // -----------------------------------------------------------------
    // B. FETCH_MODE precedence — the full grammar of the env knob, not the
    //    two values anybody thought to assert.
    //
    //    The ORDER is load-bearing for exactly one variable: the falsy set is
    //    tested first and the truthy set second, so a value in NEITHER set
    //    leaves `auto` in place. `maybe`, `2`, ` 1 ` and `TRUE` are in the
    //    corpus for that reason; none of them appears in any retained
    //    assertion.
    // -----------------------------------------------------------------
    let fetch_values = [
        None,
        Some(""),
        Some("0"),
        Some("false"),
        Some("no"),
        Some("off"),
        Some("1"),
        Some("true"),
        Some("yes"),
        Some("on"),
        Some("TRUE"),
        Some("maybe"),
        Some("2"),
        Some(" 1 "),
    ];
    for mode in modes {
        for value in fetch_values {
            for flag in [None, Some("--fetch"), Some("--no-fetch")] {
                let mut argv = vec![mode];
                if let Some(f) = flag {
                    argv.push(f);
                }
                p.add(
                    format!(
                        "B/{mode}/{}/{}",
                        value.map_or("unset", |v| if v.is_empty() { "empty" } else { v }),
                        flag.unwrap_or("-")
                    ),
                    argv,
                    vec![("LOOM_DAEMON_UPDATE_FETCH", value)],
                    Installed::Stale,
                    Repo::Source,
                    None,
                    vec![],
                    false,
                );
            }
        }
    }

    // -----------------------------------------------------------------
    // C. The drain / restart-now grammar: both flags, both env knobs, the
    //    `--timeout` argument and `--force-after-timeout`.
    //
    //    Run against a LIVE daemon, because the restart plan is only rendered
    //    on the was-running branch.
    //
    //    `--timeout` is validated by the script's own `^[0-9]+$` regex and
    //    then carried through as an OPAQUE STRING into `loom-daemon restart
    //    --drain --timeout <SECS>`. So the corpus passes a value that a parse
    //    into an integer and back would silently rewrite (`007`) alongside the
    //    ones it must reject (`abc`, `-1`, `1.5`, empty).
    // -----------------------------------------------------------------
    for drain_env in [None, Some("1"), Some("0")] {
        for now_env in [None, Some("1")] {
            for flag in [None, Some("--drain"), Some("--restart-now")] {
                for timeout in [None, Some("30"), Some("007")] {
                    for fat in [false, true] {
                        let mut argv = vec!["--dry-run"];
                        if let Some(f) = flag {
                            argv.push(f);
                        }
                        if let Some(t) = timeout {
                            argv.push("--timeout");
                            argv.push(t);
                        }
                        if fat {
                            argv.push("--force-after-timeout");
                        }
                        p.add(
                            format!(
                                "C/{}/{}/{}/{}/{}",
                                drain_env.unwrap_or("unset"),
                                now_env.unwrap_or("unset"),
                                flag.unwrap_or("-"),
                                timeout.unwrap_or("-"),
                                if fat { "fat" } else { "-" }
                            ),
                            argv,
                            vec![
                                ("LOOM_DAEMON_UPDATE_DRAIN", drain_env),
                                ("LOOM_DAEMON_UPDATE_RESTART_NOW", now_env),
                                ("LOOM_DAEMON_UPDATE_FETCH", Some("0")),
                            ],
                            Installed::Stale,
                            Repo::Source,
                            Some("--work-finder\n"),
                            vec![],
                            true,
                        );
                    }
                }
            }
        }
    }

    // The `--timeout` values the regex must REJECT, plus the conflict pair.
    for bad in ["abc", "-1", "1.5", "", " 30", "30s", "0x1e"] {
        p.add(
            format!("C/bad-timeout/{bad}"),
            vec!["--dry-run", "--timeout", bad],
            vec![],
            Installed::Stale,
            Repo::Source,
            None,
            vec![],
            false,
        );
    }
    for argv in [
        vec!["--drain", "--restart-now"],
        vec!["--restart-now", "--drain"],
        vec!["--dry-run", "--drain", "--restart-now"],
    ] {
        p.add(
            format!("C/conflict/{}", argv.join("+")),
            argv,
            vec![],
            Installed::Stale,
            Repo::Source,
            None,
            vec![],
            false,
        );
    }

    // -----------------------------------------------------------------
    // D. `.loom/.daemon.flags` replay — the file whose whole contract is
    //    "never more, never fewer".
    //
    //    The shell read it with `while read -r line; [[ -n $line ]]`, so a
    //    blank line is skipped and leading whitespace is NOT trimmed. Both
    //    are tolerances nobody wrote down; the corpus generates them.
    //
    //    Each file shape is run BOTH with a live daemon (where the replay is
    //    rendered) and without one (where the was-not-running guardrail must
    //    win over any flags on disk — the "never widens FLAGS-OFF" contract).
    // -----------------------------------------------------------------
    let flag_files: [(&str, Option<&str>); 8] = [
        ("absent", None),
        ("empty", Some("")),
        ("one", Some("--work-finder\n")),
        ("two", Some("--work-finder\n--health-gate\n")),
        ("blank-between", Some("--work-finder\n\n--health-gate\n")),
        ("no-trailing-newline", Some("--work-finder")),
        ("leading-space", Some("  --work-finder\n")),
        ("value-flag", Some("--from-config\n--interval\n30\n")),
    ];
    for (name, text) in flag_files {
        for mode in modes {
            for running in [false, true] {
                p.add(
                    format!("D/{mode}/{name}/{}", if running { "live" } else { "stopped" }),
                    vec![mode],
                    vec![("LOOM_DAEMON_UPDATE_FETCH", Some("0"))],
                    Installed::Stale,
                    Repo::Source,
                    text,
                    vec![],
                    running,
                );
            }
        }
    }

    // -----------------------------------------------------------------
    // E. The remaining flag surface, each against both modes where both are
    //    meaningful, plus the aliases, repeats and near-misses the argument
    //    loop must tolerate or refuse.
    // -----------------------------------------------------------------
    for flag in [
        "--no-restart",
        "--relaunch",
        "--prune-stale-entry-points",
        "--auto-resolve-safe-abort",
        "--force-after-timeout",
    ] {
        for mode in modes {
            for running in [false, true] {
                p.add(
                    format!("E/{mode}/{flag}/{}", if running { "live" } else { "stopped" }),
                    vec![mode, flag],
                    vec![("LOOM_DAEMON_UPDATE_FETCH", Some("0"))],
                    Installed::Stale,
                    Repo::Source,
                    Some("--work-finder\n"),
                    vec![],
                    running,
                );
            }
        }
    }
    for argv in [
        vec!["--help"],
        vec!["-h"],
        vec!["--help", "--dry-run"],
        vec!["--dry-run", "--help"],
        vec!["--nope"],
        vec!["-x"],
        vec!["--check", "--nope"],
        vec!["--nope", "--check"],
        vec!["--"],
        vec!["positional"],
        vec!["--dry-run", "--dry-run"],
        vec!["--check", "--dry-run"],
        vec!["--dry-run", "--check"],
        vec!["--check", "--force", "--no-restart", "--allow-stale"],
        vec![],
    ] {
        p.add(
            format!(
                "E/argv/{}",
                if argv.is_empty() {
                    "empty".to_string()
                } else {
                    argv.join("+")
                }
            ),
            argv,
            vec![("LOOM_DAEMON_UPDATE_FETCH", Some("0"))],
            Installed::Current,
            Repo::Source,
            None,
            vec![],
            false,
        );
    }

    // -----------------------------------------------------------------
    // F. The environment knobs that pre-seed the flag loop, each against the
    //    falsy/truthy/neither grammar the shell's `=~` tests define.
    // -----------------------------------------------------------------
    for key in [
        "LOOM_DAEMON_UPDATE_RELAUNCH",
        "LOOM_DAEMON_UPDATE_DRAIN",
        "LOOM_DAEMON_UPDATE_RESTART_NOW",
    ] {
        for value in [
            None,
            Some(""),
            Some("0"),
            Some("1"),
            Some("true"),
            Some("no"),
            Some("maybe"),
        ] {
            p.add(
                format!(
                    "F/{key}/{}",
                    value.map_or("unset", |v| if v.is_empty() { "empty" } else { v })
                ),
                vec!["--dry-run"],
                vec![(key, value), ("LOOM_DAEMON_UPDATE_FETCH", Some("0"))],
                Installed::Stale,
                Repo::Source,
                Some("--work-finder\n"),
                vec![],
                true,
            );
        }
    }

    // -----------------------------------------------------------------
    // G. The stale `loom-*` entry-point scan (#4079 / #4557), which runs on
    //    EVERY path including --check and an up-to-date no-op.
    // -----------------------------------------------------------------
    for entries in [
        vec![],
        vec!["loom-daemon-shadow"],
        vec!["loom-status", "loom-clean"],
        vec!["loomy"],       // near-miss: no hyphen, must NOT be a hit
        vec!["loom-"],       // bare prefix
        vec!["loom-daemon"], // a SECOND loom-daemon on PATH
    ] {
        for mode in modes {
            p.add(
                format!(
                    "G/{mode}/{}",
                    if entries.is_empty() {
                        "none".to_string()
                    } else {
                        entries.join("+")
                    }
                ),
                vec![mode],
                vec![
                    ("LOOM_SKIP_STALE_ENTRY_POINT_CHECK", None),
                    ("LOOM_DAEMON_UPDATE_FETCH", Some("0")),
                ],
                Installed::Stale,
                Repo::Source,
                None,
                entries.clone(),
                false,
            );
        }
    }

    // -----------------------------------------------------------------
    // H. The repo-root walk and the source-checkout gate — the refusals whose
    //    whole job is to be actionable rather than to read as "your checkout
    //    is broken".
    // -----------------------------------------------------------------
    for repo in [Repo::NotSource] {
        for mode in modes {
            for machine in [None, Some("/definitely/not/a/checkout")] {
                p.add(
                    format!(
                        "H/{mode}/{}/{}",
                        repo_name(repo),
                        if machine.is_some() { "machine" } else { "-" }
                    ),
                    vec![mode],
                    vec![
                        ("LOOM_MACHINE_CHECKOUT", machine),
                        ("LOOM_DAEMON_UPDATE_FETCH", Some("0")),
                    ],
                    Installed::Stale,
                    repo,
                    None,
                    vec![],
                    false,
                );
            }
        }
    }

    // -----------------------------------------------------------------
    // I. The #5140 self-location fallback, reached through a SYMLINK
    //    (added by #8088 — see `Case::self_located`).
    //
    //    Every case here runs from a directory holding a bare `.loom/` and no
    //    `.git`, which is the machine-state shape #5140 was reported against,
    //    so the source tree can only come from "the checkout this entry point
    //    lives in". The entry point is addressed through a second name for
    //    that checkout, which is what makes the answer say whether the
    //    implementation reports the path it was GIVEN or the one it resolves
    //    to. `canonicalize` and `cd … && pwd` agree on every input except
    //    this one; an input nobody generated is an input nobody compared.
    //
    //    The machine-mode override is in the grid because it takes precedence
    //    over the fallback, so the pair pins the ORDER of the two, not just
    //    that each works alone. `Repo::NotSource` is here because the fallback
    //    is deliberately scoped to "no checkout at all" — a resolvable
    //    checkout with no crate must still refuse rather than widen.
    // -----------------------------------------------------------------
    for mode in modes {
        for repo in [Repo::Source, Repo::NotSource] {
            for machine in [None, Some("/definitely/not/a/checkout")] {
                p.add_self_located(
                    format!(
                        "I/{mode}/{}/{}",
                        repo_name(repo),
                        if machine.is_some() { "machine" } else { "-" }
                    ),
                    vec![mode],
                    vec![
                        ("LOOM_MACHINE_CHECKOUT", machine),
                        ("LOOM_DAEMON_UPDATE_FETCH", Some("0")),
                    ],
                    Installed::Stale,
                    repo,
                );
            }
        }
    }
    // The installed-binary shape is varied once per mode as well: the fallback
    // message is printed before the staleness comparison, and a corpus that
    // only ever ran one shape could not tell an ordering change from a
    // rendering one.
    for mode in modes {
        for installed in [Installed::Current, Installed::Absent] {
            p.add_self_located(
                format!("I/{mode}/{}", installed_name(installed)),
                vec![mode],
                vec![("LOOM_DAEMON_UPDATE_FETCH", Some("0"))],
                installed,
                Repo::Source,
            );
        }
    }

    cases
}

/// Regenerate `fixtures/daemon_update_shell_oracle.jsonl` from the pre-port
/// shell. Ignored by default; see the module docs for the exact command.
#[test]
#[ignore = "regenerates the frozen oracle; needs the pre-port shell via LOOM_UPDATE_ORACLE_SHELL"]
fn regenerate_oracle() {
    let shell = std::env::var("LOOM_UPDATE_ORACLE_SHELL")
        .expect("set LOOM_UPDATE_ORACLE_SHELL to the pre-port loom-daemon-update.sh");
    let shell = PathBuf::from(shell);
    assert!(shell.is_file(), "no such shell: {}", shell.display());

    // The bash the oracle was produced by is provenance, not trivia: bash 5.2
    // changed what `&` means in the replacement half of `${var//pat/repl}`,
    // and macOS's /bin/bash is still 3.2. An oracle generated under the wrong
    // one would answer differently from CI's.
    let bash = std::env::var("LOOM_UPDATE_ORACLE_BASH").unwrap_or_else(|_| "/bin/bash".to_string());
    let bash_version = Command::new(&bash)
        .args(["-c", "echo -n \"$BASH_VERSION\""])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
        .unwrap_or_default();
    assert!(
        !bash_version.starts_with("3."),
        "refusing to freeze an oracle under bash {bash_version}: the retired script's \
         behaviour differs on bash >= 5.2, which is what CI runs. Set \
         LOOM_UPDATE_ORACLE_BASH to a bash >= 5.2."
    );

    // The rev the reference shell came from — the one thing that makes these
    // answers attributable. `git show <rev>:defaults/scripts/cli/loom-daemon-update.sh`
    // recovers exactly the implementation that produced them.
    let reference_rev = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();

    let cases = build_corpus();
    let mut out = String::new();
    out.push_str(&serde_json::json!({"_meta": {
        "subject": "loom-daemon daemon-update (defaults/scripts/cli/loom-daemon-update.sh)",
        "reference_impl": shell.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
        "reference_rev": reference_rev,
        "bash": bash,
        "bash_version": bash_version,
        "generated_by": "cargo test -p loom-daemon --test differential_daemon_update -- --ignored regenerate_oracle",
        "argv0": ARGV0,
        "fixed_path": FIXED_PATH,
        "fixed_target": FIXED_TARGET,
        "cases": cases.len(),
        "note": "Answers are the PRE-PORT shell's. Paths are normalised to {ROOT}, the pinned \
                 checkout HEAD to {HEAD}. Regenerating this file against the PORT would make \
                 the test tautological.",
    }}).to_string());
    out.push('\n');

    for case in &cases {
        let answer = run_case(case, Path::new(&bash), &[shell.display().to_string()]);
        let env: serde_json::Map<String, serde_json::Value> = case
            .env
            .iter()
            .map(|(k, v)| {
                (
                    k.clone(),
                    v.clone()
                        .map_or(serde_json::Value::Null, serde_json::Value::String),
                )
            })
            .collect();
        let mut rec = serde_json::json!({
            "id": case.id,
            "argv": case.argv,
            "env": env,
            "installed": installed_name(case.installed),
            "repo": repo_name(case.repo),
            "stale_entry_points": case.stale_entry_points,
            "running": case.running,
            "rc": answer.rc,
            "stdout": answer.stdout,
            "stderr": answer.stderr,
        });
        if let Some(t) = &case.flags_file {
            rec["flags_file"] = serde_json::Value::String(t.clone());
        }
        // Written only when true, so re-freezing leaves the pre-#8088 records
        // byte-identical and a diff of this fixture stays a diff of the cases
        // that actually changed.
        if case.self_located {
            rec["self_located"] = serde_json::Value::Bool(true);
        }
        out.push_str(&rec.to_string());
        out.push('\n');
    }

    let dest = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/daemon_update_shell_oracle.jsonl");
    std::fs::write(&dest, out).expect("write oracle");
    println!("wrote {} cases to {}", cases.len(), dest.display());
}

/// The frozen corpus must still be the corpus [`build_corpus`] describes.
///
/// Without this, an edit to the generator and a stale fixture drift apart
/// silently: the replay would keep passing against yesterday's cases while the
/// grammar it claims to cover had moved.
#[test]
fn the_frozen_cases_are_the_ones_the_generator_builds() {
    let (_meta, frozen) = load_oracle();
    let built = build_corpus();
    assert_eq!(
        frozen.len(),
        built.len(),
        "the frozen oracle has {} cases and the generator now builds {} — regenerate it \
         (see the module docs) rather than editing the fixture by hand",
        frozen.len(),
        built.len()
    );
    for ((frozen_case, _), built_case) in frozen.iter().zip(built.iter()) {
        assert_eq!(
            frozen_case, built_case,
            "frozen case {} no longer matches the generator",
            frozen_case.id
        );
    }
}
