#!/usr/bin/env bash
# check-doc-tocs.sh — keep a generated table of contents in every large doc.
#
# Why (#7739): Claude reads a doc reached through a reference by PREVIEWING it
# (e.g. `head -100`) rather than loading the whole file. Without a table of
# contents at the top, that preview reveals only whatever happens to appear in
# the first hundred lines — for daemon-reference.md, one heading out of dozens.
# Anthropic's skill-authoring guidance calls for a TOC on any reference file
# over 100 lines for exactly this reason. Every role prompt and several slash
# commands link into these docs, often by deep anchor, so this is a hot path.
#
# Generated, not hand-written, and CI-checked: a hand-maintained TOC drifts the
# moment someone adds a section, and a stale TOC is worse than none because it
# tells the reader a section does not exist. (#7711 shipped two hand-written
# figures that were wrong within a day; same failure mode.)
#
# The TOC lists TOP-LEVEL (`##`) sections only. A full heading dump would
# recreate the problem it solves.
#
# File set (#7753 extends #7739's defaults/docs/*.md to the agent-facing
# prompt set too — bigger and hotter, and #7724 confirmed these are the files
# that actually dominate agent context):
#   - defaults/docs/*.md               (reference docs, #7739's original scope)
#   - defaults/.claude/commands/loom/*.md, EXCEPT bump.md (a generic,
#     non-Loom-specific command — #7724's canonical 33-file prompt set is 18
#     role prompts + 15 command-only files, not 34)
#
# defaults/roles/*.md (other than README.md, a docs index) are NOT globbed
# separately: every one of them is a symlink into
# defaults/.claude/commands/loom/ (confirmed structurally, not by name list —
# see check-markdown-token-budget.sh, #7724/#7725), so generating on the
# commands/loom/ side is automatically visible through the symlink. Writing
# through defaults/roles/<name>.md instead would replace the symlink with a
# standalone file via `mv` and desynchronize the pair.
#
# Usage:
#   check-doc-tocs.sh           Fail if any doc's TOC is missing or stale.
#   check-doc-tocs.sh --fix     Insert/refresh the TOC in place.
#   check-doc-tocs.sh --threshold N   Minimum line count to require a TOC (default 500).
#   check-doc-tocs.sh --help
#
# Exit codes: 0 = all TOCs current; 1 = missing/stale (names printed); 2 = bad args.
#
# Portability: this runs on developer machines, and macOS ships bash 3.2. No
# associative arrays, no ${x,,}, no mapfile — see #7717 / #7730 for what those
# cost here.

set -euo pipefail

BEGIN_MARK='<!-- toc:begin generated by scripts/check-doc-tocs.sh --fix; do not edit by hand -->'
END_MARK='<!-- toc:end -->'

MODE="check"
THRESHOLD=500

while [ $# -gt 0 ]; do
  case "$1" in
    --fix)       MODE="fix"; shift ;;
    --threshold) THRESHOLD="${2:?--threshold needs a value}"; shift 2 ;;
    --help|-h)   sed -n '2,46p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)           echo "check-doc-tocs: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if ! ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
  ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi
cd "$ROOT"

# GitHub's heading anchor: lowercase, drop anything that is not alphanumeric,
# underscore, space or hyphen (backticks, punctuation, emphasis markers) —
# underscore is kept because GitHub's own slugger preserves it — spaces -> hyphens.
#
# ORDER OF OPERATIONS MATTERS (#7753). GitHub's slugger does NOT trim: it strips
# the disallowed characters and then turns EVERY remaining space into a hyphen,
# including one that is now leading because the character in front of it was
# dropped. `## ⛔ STOP! READ THIS FIRST - …` therefore anchors as
# `#-stop-read-this-first---…`, with a leading hyphen standing in for the
# stripped emoji's trailing space. Trimming after the strip (which this did
# until #7753) produced `#stop-read-this-first---…` and generated a TOC full of
# self-referential dead links in every emoji-headed prompt — the exact class of
# heading this file set uses for its warnings (⛔, ⚠️, 🚫).
#
# The one trim that IS correct happens BEFORE the strip: CommonMark trims the
# heading text itself, so `##   Foo  ` is the heading "Foo" and never reaches
# the slugger with its surrounding whitespace attached.
slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -e 's/`//g' -e 's/\[\([^]]*\)\](\([^)]*\))/\1/g' \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | sed -e 's/[^a-z0-9_ -]//g' \
    | sed -e 's/ /-/g'
}

# Emit the TOC body for one file. Duplicate slugs get GitHub's -1, -2 suffixes;
# tracked in a newline-delimited string because bash 3.2 has no assoc arrays.
build_toc() {
  file="$1"
  seen=""
  printf '%s\n' "$BEGIN_MARK"
  printf '**Contents**\n\n'
  # Skip headings inside fenced code blocks — by CommonMark's fence rules, not
  # by toggling on every ``` line (#7753). A closing fence carries NO info
  # string and is at least as long as its opener, so the inner ```bash of a
  # ```bash block that quotes a shell heredoc does not close anything. Toggling
  # blind inverts the fence state from that point on: hermit-patterns.md's
  # proposal templates made the generator emit `## Goal Discovery Scripts` (which
  # GitHub renders inside a code block, so the anchor does not exist) while
  # hiding the template headings that GitHub does render.
  #
  # Written with substr/while rather than `{n,m}` intervals: old awks (mawk 1.3.3,
  # the BSD awk on macOS) do not support interval expressions without a flag.
  awk '
    {
      line = $0
      indent = 0
      while (indent < length(line) && substr(line, indent + 1, 1) == " ") indent++
      body = substr(line, indent + 1)
      fence_char = substr(body, 1, 1)
      ticks = 0
      # Up to three leading spaces still opens/closes a fence; four makes it an
      # indented code block, which cannot contain a heading either way.
      if (indent <= 3 && (fence_char == "`" || fence_char == "~")) {
        while (substr(body, ticks + 1, 1) == fence_char) ticks++
        if (ticks < 3) ticks = 0
      }
      if (infence) {
        if (ticks >= open_len && fence_char == open_char) {
          rest = substr(body, ticks + 1)
          gsub(/[ \t]/, "", rest)
          if (rest == "") infence = 0
        }
        next
      }
      if (ticks > 0) { infence = 1; open_char = fence_char; open_len = ticks; next }
      if (indent == 0 && body ~ /^## /) { sub(/^## /, "", body); print body }
    }
  ' "$file" | while IFS= read -r heading; do
    [ -n "$heading" ] || continue
    base="$(slugify "$heading")"
    [ -n "$base" ] || continue
    n="$(printf '%s\n' "$seen" | grep -c "^$base\$" || true)"
    if [ "$n" -eq 0 ]; then slug="$base"; else slug="$base-$n"; fi
    seen="$seen
$base"
    printf -- '- [%s](#%s)\n' "$heading" "$slug"
  done
  printf '%s\n' "$END_MARK"
}

# Rewrite one file with a current TOC. An existing marker block is replaced in
# place; otherwise the TOC is inserted immediately before the first `##`
# heading, which keeps it under the title and any intro paragraph.
#
# Spliced with head/tail line arithmetic rather than awk: awk -v cannot carry a
# multi-line string (BSD awk rejects it outright), and this needs no temp file.
render() {
  file="$1"
  toc="$(build_toc "$file")"
  b_line="$(grep -nF "$BEGIN_MARK" "$file" | head -1 | cut -d: -f1)"
  if [ -n "$b_line" ]; then
    e_line="$(grep -nF "$END_MARK" "$file" | head -1 | cut -d: -f1)"
    if [ -z "$e_line" ] || [ "$e_line" -lt "$b_line" ]; then
      echo "check-doc-tocs: $file has a toc:begin marker with no matching toc:end" >&2
      return 1
    fi
    head -n "$((b_line - 1))" "$file"
    printf '%s\n' "$toc"
    tail -n "+$((e_line + 1))" "$file"
  else
    h_line="$(grep -n '^## ' "$file" | head -1 | cut -d: -f1)"
    if [ -z "$h_line" ]; then
      cat "$file"
      return 0
    fi
    head -n "$((h_line - 1))" "$file"
    printf '%s\n\n' "$toc"
    tail -n "+$h_line" "$file"
  fi
}

qualifies() {
  [ "$(awk 'END { print NR }' "$1")" -gt "$THRESHOLD" ]
}

stale=""
fixed=0
checked=0

for f in defaults/docs/*.md defaults/.claude/commands/loom/*.md; do
  [ -f "$f" ] || continue
  case "$f" in
    */bump.md) continue ;;  # generic, non-Loom-specific — not part of the prompt set
  esac
  qualifies "$f" || continue
  checked=$((checked + 1))
  rendered="$(render "$f")"
  if [ "$rendered" = "$(cat "$f")" ]; then
    continue
  fi
  if [ "$MODE" = "fix" ]; then
    printf '%s\n' "$rendered" > "$f.toctmp"
    mv "$f.toctmp" "$f"
    echo "  updated $f"
    fixed=$((fixed + 1))
  else
    stale="$stale $f"
  fi
done

if [ "$MODE" = "fix" ]; then
  echo "check-doc-tocs: $fixed of $checked doc(s) updated (threshold $THRESHOLD lines)."
  exit 0
fi

if [ -n "$stale" ]; then
  {
    echo "check-doc-tocs: FAIL — these docs have a missing or stale table of contents:"
    for f in $stale; do echo "  $f"; done
    echo ""
    echo "A doc reached through a reference is often PREVIEWED, not read whole, so the"
    echo "TOC is what tells the reader which sections exist. A stale one is worse than"
    echo "none: it claims a section is absent when it is not."
    echo ""
    echo "Fix with:  scripts/check-doc-tocs.sh --fix"
    echo "Do not hand-edit the block between the toc:begin / toc:end markers."
  } >&2
  exit 1
fi

echo "check-doc-tocs: OK — $checked doc(s) over $THRESHOLD lines have a current TOC."
exit 0
