#!/usr/bin/env bash
# check-doc-tocs.sh — keep a generated table of contents in every large doc.
#
# Why (#7739): Claude reads a doc reached through a reference by PREVIEWING it
# (e.g. `head -100`) rather than loading the whole file. Without a table of
# contents at the top, that preview reveals only whatever happens to appear in
# the first hundred lines — for daemon-reference.md, one heading out of dozens.
# Anthropic's skill-authoring guidance calls for a TOC on any reference file
# over 100 lines for exactly this reason. Every role prompt and several slash
# commands link into these docs, often by deep anchor, so this is a hot path.
#
# Generated, not hand-written, and CI-checked: a hand-maintained TOC drifts the
# moment someone adds a section, and a stale TOC is worse than none because it
# tells the reader a section does not exist. (#7711 shipped two hand-written
# figures that were wrong within a day; same failure mode.)
#
# The TOC lists TOP-LEVEL (`##`) sections only. A full heading dump would
# recreate the problem it solves.
#
# Usage:
#   check-doc-tocs.sh           Fail if any doc's TOC is missing or stale.
#   check-doc-tocs.sh --fix     Insert/refresh the TOC in place.
#   check-doc-tocs.sh --threshold N   Minimum line count to require a TOC (default 500).
#   check-doc-tocs.sh --help
#
# Exit codes: 0 = all TOCs current; 1 = missing/stale (names printed); 2 = bad args.
#
# Portability: this runs on developer machines, and macOS ships bash 3.2. No
# associative arrays, no ${x,,}, no mapfile — see #7717 / #7730 for what those
# cost here.

set -euo pipefail

BEGIN_MARK='<!-- toc:begin generated by scripts/check-doc-tocs.sh --fix; do not edit by hand -->'
END_MARK='<!-- toc:end -->'

MODE="check"
THRESHOLD=500

while [ $# -gt 0 ]; do
  case "$1" in
    --fix)       MODE="fix"; shift ;;
    --threshold) THRESHOLD="${2:?--threshold needs a value}"; shift 2 ;;
    --help|-h)   sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)           echo "check-doc-tocs: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if ! ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
  ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi
cd "$ROOT"

# GitHub's heading anchor: lowercase, drop anything that is not alphanumeric,
# underscore, space or hyphen (backticks, punctuation, emphasis markers) —
# underscore is kept because GitHub's own slugger preserves it — spaces -> hyphens.
slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -e 's/`//g' -e 's/\[\([^]]*\)\](\([^)]*\))/\1/g' \
    | sed -e 's/[^a-z0-9_ -]//g' \
    | sed -e 's/^ *//' -e 's/ *$//' -e 's/ /-/g'
}

# Emit the TOC body for one file. Duplicate slugs get GitHub's -1, -2 suffixes;
# tracked in a newline-delimited string because bash 3.2 has no assoc arrays.
build_toc() {
  file="$1"
  seen=""
  printf '%s\n' "$BEGIN_MARK"
  printf '**Contents**\n\n'
  # Skip headings inside fenced code blocks.
  awk '
    /^```/ { infence = !infence; next }
    !infence && /^## / { sub(/^## /, ""); print }
  ' "$file" | while IFS= read -r heading; do
    [ -n "$heading" ] || continue
    base="$(slugify "$heading")"
    [ -n "$base" ] || continue
    n="$(printf '%s\n' "$seen" | grep -c "^$base\$" || true)"
    if [ "$n" -eq 0 ]; then slug="$base"; else slug="$base-$n"; fi
    seen="$seen
$base"
    printf -- '- [%s](#%s)\n' "$heading" "$slug"
  done
  printf '%s\n' "$END_MARK"
}

# Rewrite one file with a current TOC. An existing marker block is replaced in
# place; otherwise the TOC is inserted immediately before the first `##`
# heading, which keeps it under the title and any intro paragraph.
#
# Spliced with head/tail line arithmetic rather than awk: awk -v cannot carry a
# multi-line string (BSD awk rejects it outright), and this needs no temp file.
render() {
  file="$1"
  toc="$(build_toc "$file")"
  b_line="$(grep -nF "$BEGIN_MARK" "$file" | head -1 | cut -d: -f1)"
  if [ -n "$b_line" ]; then
    e_line="$(grep -nF "$END_MARK" "$file" | head -1 | cut -d: -f1)"
    if [ -z "$e_line" ] || [ "$e_line" -lt "$b_line" ]; then
      echo "check-doc-tocs: $file has a toc:begin marker with no matching toc:end" >&2
      return 1
    fi
    head -n "$((b_line - 1))" "$file"
    printf '%s\n' "$toc"
    tail -n "+$((e_line + 1))" "$file"
  else
    h_line="$(grep -n '^## ' "$file" | head -1 | cut -d: -f1)"
    if [ -z "$h_line" ]; then
      cat "$file"
      return 0
    fi
    head -n "$((h_line - 1))" "$file"
    printf '%s\n\n' "$toc"
    tail -n "+$h_line" "$file"
  fi
}

qualifies() {
  [ "$(awk 'END { print NR }' "$1")" -gt "$THRESHOLD" ]
}

stale=""
fixed=0
checked=0

for f in defaults/docs/*.md; do
  [ -f "$f" ] || continue
  qualifies "$f" || continue
  checked=$((checked + 1))
  rendered="$(render "$f")"
  if [ "$rendered" = "$(cat "$f")" ]; then
    continue
  fi
  if [ "$MODE" = "fix" ]; then
    printf '%s\n' "$rendered" > "$f.toctmp"
    mv "$f.toctmp" "$f"
    echo "  updated $f"
    fixed=$((fixed + 1))
  else
    stale="$stale $f"
  fi
done

if [ "$MODE" = "fix" ]; then
  echo "check-doc-tocs: $fixed of $checked doc(s) updated (threshold $THRESHOLD lines)."
  exit 0
fi

if [ -n "$stale" ]; then
  {
    echo "check-doc-tocs: FAIL — these docs have a missing or stale table of contents:"
    for f in $stale; do echo "  $f"; done
    echo ""
    echo "A doc reached through a reference is often PREVIEWED, not read whole, so the"
    echo "TOC is what tells the reader which sections exist. A stale one is worse than"
    echo "none: it claims a section is absent when it is not."
    echo ""
    echo "Fix with:  scripts/check-doc-tocs.sh --fix"
    echo "Do not hand-edit the block between the toc:begin / toc:end markers."
  } >&2
  exit 1
fi

echo "check-doc-tocs: OK — $checked doc(s) over $THRESHOLD lines have a current TOC."
exit 0
