#!/usr/bin/env bash
# Regression test for issues #3588 and #3611: `install.sh --quick` must not
# strand or mangle a user's uncommitted changes across the uninstall→reinstall
# stash/pop + index-reconcile cycle.
#
# #3588: The uninstall→init round-trip rewrites .gitignore non-reversibly
# (uninstall strips Loom patterns mid-block + collapses blanks; init re-appends
# them at EOF). That moves lines relative to HEAD, so a stashed .gitignore hunk
# no longer has a matching 3-way base and `git stash pop` conflicts. The old code
# silenced the pop with `2>/dev/null`, hiding the conflict and stranding the edit.
# The fix restores .gitignore to HEAD before popping (so the user's hunk applies
# cleanly) and re-appends the Loom patterns idempotently, and surfaces real
# conflicts with a recovery path instead of hiding them.
#
# #3611 (Scenarios 7-10): two further defects in the same machinery.
#   Defect 1 — a plain `git stash pop` re-applied every stashed hunk as
#   *unstaged*, so a caller who had a .gitignore edit STAGED before the reinstall
#   got it back unstaged (partial staging silently flattened). Fix: pop --index,
#   which reproduces the caller's staged/unstaged split.
#   Defect 2 — `.loom/install-metadata.json` (generated by finalize_quick_install,
#   not shipped in defaults/) was left as a staged deletion + untracked copy
#   (`D` + `??`) because the ownership-scoped index reconcile never covered it.
#   Committed as-is it untracked a verify_install critical file. Fix: an explicit
#   reconcile that unstages the staged deletion so it reappears as a tracked
#   modification.
#
# Requirements: bash, git, and a built loom-daemon binary (target/release).
#   Skips (exit 0) if the daemon binary is not present, mirroring the installer's
#   own build-on-demand behavior — CI that builds the daemon will exercise it.
#
# Usage: bash scripts/test-install-quick-gitignore-stash.sh

set -uo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

passed=0
failed=0

pass() { echo -e "${GREEN}✓${NC} $1"; passed=$((passed + 1)); }
fail() { echo -e "${RED}✗${NC} $1"; failed=$((failed + 1)); }
warn() { echo -e "${YELLOW}!${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOOM_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTALL_SCRIPT="$LOOM_ROOT/install.sh"

if [[ ! -f "$LOOM_ROOT/target/release/loom-daemon" ]]; then
  warn "loom-daemon binary not built (target/release/loom-daemon missing) — skipping #3588 install.sh --quick test"
  exit 0
fi

TEST_DIR="$(mktemp -d)"
cleanup() { [[ -n "${TEST_DIR:-}" && -d "$TEST_DIR" ]] && rm -rf "$TEST_DIR"; }
trap cleanup EXIT

# Create a target repo with a tracked .gitignore (containing a couple of the
# Loom ephemeral patterns mid-block, as a real committed .gitignore would after
# a prior install), install Loom, and commit so we have a clean baseline.
setup_repo() {
  local w="$1"
  git init -q "$w"
  git -C "$w" config user.email test@example.com
  git -C "$w" config user.name "Test User"
  printf 'node_modules/\n.loom/state.json\n.loom/worktrees/\n*.log\ndist/\n' >"$w/.gitignore"
  echo "hello" >"$w/README.md"
  git -C "$w" add -A
  git -C "$w" commit -qm "init"
  "$INSTALL_SCRIPT" -y --quick "$w" >/dev/null 2>&1
  git -C "$w" add -A
  git -C "$w" commit -qm "loom install" >/dev/null 2>&1
}

echo "======================================"
echo "Issue #3588: install.sh --quick .gitignore stash/pop"
echo "======================================"
echo ""

# --------------------------------------------------------------------------
# Scenario 1 (primary): uncommitted .gitignore edit survives the reinstall.
# --------------------------------------------------------------------------
R1="$TEST_DIR/tracked-gitignore-edit"
setup_repo "$R1"
echo "my-local-dir/" >>"$R1/.gitignore"
"$INSTALL_SCRIPT" -y --quick "$R1" >/dev/null 2>&1

if grep -qxF "my-local-dir/" "$R1/.gitignore"; then
  pass "user .gitignore edit ('my-local-dir/') survives --quick reinstall"
else
  fail "user .gitignore edit stranded after --quick reinstall (#3588)"
fi
if [[ "$(git -C "$R1" stash list | wc -l | tr -d ' ')" == "0" ]]; then
  pass "stash consumed (git stash list empty)"
else
  fail "stash not consumed — user change left in stash (#3588)"
fi
if grep -qxF ".loom/worktrees/" "$R1/.gitignore" && grep -qxF ".loom/logs/" "$R1/.gitignore"; then
  pass "current Loom ephemeral patterns present after reinstall"
else
  fail "Loom ephemeral patterns missing after reinstall"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 2: idempotency — a second --quick run leaves .gitignore byte-stable.
# --------------------------------------------------------------------------
R2="$TEST_DIR/idempotent"
setup_repo "$R2"
echo "my-local-dir/" >>"$R2/.gitignore"
"$INSTALL_SCRIPT" -y --quick "$R2" >/dev/null 2>&1
cp "$R2/.gitignore" "$TEST_DIR/gi-run1"
"$INSTALL_SCRIPT" -y --quick "$R2" >/dev/null 2>&1
if diff -q "$TEST_DIR/gi-run1" "$R2/.gitignore" >/dev/null; then
  pass ".gitignore byte-stable across a second --quick run"
else
  fail ".gitignore churned on second --quick run (not idempotent)"
fi
if grep -qxF "my-local-dir/" "$R2/.gitignore" && \
   [[ "$(git -C "$R2" stash list | wc -l | tr -d ' ')" == "0" ]]; then
  pass "user edit preserved and no phantom stash after second run"
else
  fail "user edit lost or phantom stash after second run"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 3: unrelated (non-.gitignore) edit still restores cleanly.
# --------------------------------------------------------------------------
R3="$TEST_DIR/readme-edit"
setup_repo "$R3"
echo "user readme line" >>"$R3/README.md"
"$INSTALL_SCRIPT" -y --quick "$R3" >/dev/null 2>&1
if grep -qxF "user readme line" "$R3/README.md" && \
   [[ "$(git -C "$R3" stash list | wc -l | tr -d ' ')" == "0" ]]; then
  pass "unrelated README.md edit restored cleanly (no regression)"
else
  fail "unrelated README.md edit not restored"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 4: .gitignore untracked at HEAD — reset is skipped, no error raised.
# --------------------------------------------------------------------------
R4="$TEST_DIR/untracked-gitignore"
git init -q "$R4"
git -C "$R4" config user.email test@example.com
git -C "$R4" config user.name "Test User"
echo "hello" >"$R4/README.md"
git -C "$R4" add README.md
git -C "$R4" commit -qm "init"
"$INSTALL_SCRIPT" -y --quick "$R4" >/dev/null 2>&1
# Keep .gitignore untracked at HEAD.
git -C "$R4" add -A
git -C "$R4" reset -q -- .gitignore
git -C "$R4" commit -qm "loom minus gitignore" >/dev/null 2>&1
echo "another readme line" >>"$R4/README.md"
if "$INSTALL_SCRIPT" -y --quick "$R4" >/dev/null 2>&1 && \
   grep -qxF "another readme line" "$R4/README.md"; then
  pass "untracked-.gitignore reinstall completes cleanly and restores edit"
else
  fail "untracked-.gitignore reinstall failed"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 5 (conflict path): a genuine, unresolvable stash-pop conflict must
# NOT abort the installer. The user customizes a Loom-managed tracked file
# (.loom/roles/builder.md) and commits it, then makes an uncommitted edit to
# the same region. The reinstall's `init` overwrites that file with canonical
# content, so the stashed hunk no longer 3-way merges and `git stash pop`
# conflicts for real. The installer must: (a) exit 0, (b) preserve the stash,
# (c) print the recovery instructions (`git stash show -p`) and the completion
# banner — instead of dying mid-stream under `set -euo pipefail`.
#
# This assertion FAILS against the pre-fix PR code (the plain `VAR="$(...)"`
# capture let a conflicting pop trip `set -e` on the assignment, exiting 1
# before the conflict branch) and PASSES after the `if`-condition fix.
R5="$TEST_DIR/genuine-conflict"
setup_repo "$R5"
CONFLICT_FILE=".loom/roles/builder.md"
if [[ -f "$R5/$CONFLICT_FILE" ]]; then
  # Customize the managed file and commit so init's rewrite diverges from HEAD.
  { echo "USER CUSTOM SENTINEL LINE"; cat "$R5/$CONFLICT_FILE"; } >"$R5/$CONFLICT_FILE.tmp"
  mv "$R5/$CONFLICT_FILE.tmp" "$R5/$CONFLICT_FILE"
  git -C "$R5" add -A
  git -C "$R5" commit -qm "customize managed file" >/dev/null 2>&1
  # Uncommitted edit to the same first line -> stashed, then conflicts on pop.
  perl -0pi -e 's/USER CUSTOM SENTINEL LINE/USER CUSTOM SENTINEL LINE EDITED/' "$R5/$CONFLICT_FILE"

  CONFLICT_OUT="$TEST_DIR/conflict-out.txt"
  "$INSTALL_SCRIPT" -y --quick "$R5" >"$CONFLICT_OUT" 2>&1
  CONFLICT_EXIT=$?

  if [[ $CONFLICT_EXIT -eq 0 ]]; then
    pass "genuine stash-pop conflict: installer exits 0 (does not abort under set -e)"
  else
    fail "genuine stash-pop conflict: installer exited $CONFLICT_EXIT (set -e aborted the conflict branch — #3588)"
  fi
  if [[ "$(git -C "$R5" stash list | wc -l | tr -d ' ')" != "0" ]]; then
    pass "genuine stash-pop conflict: stash preserved for manual recovery"
  else
    fail "genuine stash-pop conflict: stash lost (user changes unrecoverable)"
  fi
  if grep -q "git stash show -p" "$CONFLICT_OUT" && grep -q "preserved in the stash" "$CONFLICT_OUT"; then
    pass "genuine stash-pop conflict: recovery instructions + stash ref printed"
  else
    fail "genuine stash-pop conflict: recovery instructions not printed (dead conflict branch — #3588)"
  fi
  if grep -q "Quick reinstallation complete" "$CONFLICT_OUT"; then
    pass "genuine stash-pop conflict: completion banner still printed"
  else
    fail "genuine stash-pop conflict: completion banner missing (installer died mid-stream — #3588)"
  fi
else
  warn "managed file $CONFLICT_FILE not present after install — skipping conflict-path scenario"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 6 (issue #3590): install -> uninstall -> install on a repo with a
# committed, customized .gitignore is byte-identical, and uninstall removes the
# entire Loom-managed block (marker-delimited). This asserts the round-trip is
# reversible at the byte level — the root cause #3589 only worked around.
#
# FAILS against pre-#3590 code: uninstall stripped a drifted 4-pattern subset +
# reflowed blank lines, and init re-appended at EOF, so the block moved and
# ~26 patterns were left behind.
# --------------------------------------------------------------------------
UNINSTALL_SCRIPT="$LOOM_ROOT/scripts/uninstall-loom.sh"
R6="$TEST_DIR/roundtrip-byte-identical"
git init -q "$R6"
git -C "$R6" config user.email test@example.com
git -C "$R6" config user.name "Test User"
# A customized consumer .gitignore with intentional spacing and no Loom content.
printf '# consumer rules\nnode_modules/\ntarget/\n\n*.log\ndist/\n' >"$R6/.gitignore"
echo "hello" >"$R6/README.md"
git -C "$R6" add -A
git -C "$R6" commit -qm "init"
# First install writes the marked Loom block; commit it as the baseline.
"$INSTALL_SCRIPT" -y --quick "$R6" >/dev/null 2>&1
git -C "$R6" add -A
git -C "$R6" commit -qm "loom install" >/dev/null 2>&1
cp "$R6/.gitignore" "$TEST_DIR/gi-baseline"

# Sanity: the marked block exists after install.
if grep -qxF "# >>> loom-managed (do not edit) >>>" "$R6/.gitignore" && \
   grep -qxF "# <<< loom-managed <<<" "$R6/.gitignore"; then
  pass "install writes a marker-delimited Loom block"
else
  fail "install did not write marker-delimited Loom block (#3590)"
fi

# install -> uninstall -> install (a second --quick reinstall runs uninstall+init
# internally). With no user edits it must be a byte-for-byte no-op.
"$INSTALL_SCRIPT" -y --quick "$R6" >/dev/null 2>&1
if diff -q "$TEST_DIR/gi-baseline" "$R6/.gitignore" >/dev/null; then
  pass ".gitignore is byte-identical after install -> uninstall -> install (#3590)"
else
  fail ".gitignore changed across the round-trip (not byte-stable — #3590)"
  diff "$TEST_DIR/gi-baseline" "$R6/.gitignore" || true
fi
if git -C "$R6" diff --exit-code -- .gitignore >/dev/null 2>&1; then
  pass "git diff shows no .gitignore movement after round-trip"
else
  fail "git diff shows .gitignore movement after round-trip (#3590)"
fi

# Uninstall alone must remove the ENTIRE Loom block (markers + all patterns),
# leaving the user's consumer content (and its blank line) verbatim.
"$UNINSTALL_SCRIPT" --yes --local "$R6" >/dev/null 2>&1 || true
if [[ -f "$R6/.gitignore" ]]; then
  if grep -q "loom-managed" "$R6/.gitignore" 2>/dev/null || \
     grep -qxF ".loom/worktrees/" "$R6/.gitignore" 2>/dev/null || \
     grep -qxF ".loom/logs/" "$R6/.gitignore" 2>/dev/null || \
     grep -q "# Loom runtime state" "$R6/.gitignore" 2>/dev/null; then
    fail "uninstall left residual Loom patterns in .gitignore (#3590)"
  else
    pass "uninstall removed the entire Loom-managed block (no residue)"
  fi
  if diff -q <(printf '# consumer rules\nnode_modules/\ntarget/\n\n*.log\ndist/\n') \
       "$R6/.gitignore" >/dev/null; then
    pass "uninstall preserved consumer content + spacing verbatim"
  else
    fail "uninstall mutated consumer content/spacing outside the block (#3590)"
    diff <(printf '# consumer rules\nnode_modules/\ntarget/\n\n*.log\ndist/\n') "$R6/.gitignore" || true
  fi
else
  fail "uninstall hard-deleted a .gitignore that still had consumer content (#3590)"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 7 (#3611 Defect 1): a STAGED .gitignore edit is restored STILL
# STAGED after a --quick reinstall (git stash pop --index preserves the split).
# FAILS against the plain-`git stash pop` code, which re-applies the edit as
# unstaged.
# --------------------------------------------------------------------------
R7="$TEST_DIR/staged-gitignore-edit"
setup_repo "$R7"
echo "staged-local-dir/" >>"$R7/.gitignore"
git -C "$R7" add .gitignore
"$INSTALL_SCRIPT" -y --quick "$R7" >/dev/null 2>&1
if grep -qxF "staged-local-dir/" "$R7/.gitignore"; then
  pass "staged .gitignore edit survives --quick reinstall"
else
  fail "staged .gitignore edit lost after --quick reinstall (#3611)"
fi
if git -C "$R7" diff --staged --name-only | grep -qxF ".gitignore"; then
  pass "staged .gitignore edit restored STILL STAGED (pop --index, #3611)"
else
  fail "staged .gitignore edit came back unstaged (plain pop dropped the split — #3611)"
fi
if [[ "$(git -C "$R7" stash list | wc -l | tr -d ' ')" == "0" ]]; then
  pass "stash consumed after staged-edit reinstall"
else
  fail "stash not consumed after staged-edit reinstall (#3611)"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 8 (#3611 Defect 1): an UNSTAGED .gitignore edit stays UNSTAGED after
# a reinstall (pop --index must not spuriously stage an unstaged hunk).
# --------------------------------------------------------------------------
R8="$TEST_DIR/unstaged-stays-unstaged"
setup_repo "$R8"
echo "unstaged-local-dir/" >>"$R8/.gitignore"
"$INSTALL_SCRIPT" -y --quick "$R8" >/dev/null 2>&1
if grep -qxF "unstaged-local-dir/" "$R8/.gitignore"; then
  pass "unstaged .gitignore edit survives --quick reinstall"
else
  fail "unstaged .gitignore edit lost after --quick reinstall (#3611)"
fi
if git -C "$R8" diff --staged --name-only | grep -qxF ".gitignore"; then
  fail "unstaged .gitignore edit was spuriously STAGED after reinstall (#3611)"
else
  pass "unstaged .gitignore edit stays UNSTAGED after reinstall (#3611)"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 9 (#3611 Defect 2): .loom/install-metadata.json stays a tracked
# modification after reinstall — never a `D` staged-deletion + `??` untracked
# pair. We first commit a divergent (older-looking) metadata so the reinstall's
# regenerated file differs from HEAD and the tracked modification is observable.
# FAILS against pre-fix code: the ownership-scoped reconcile skips the generated
# metadata, leaving `D` + `??`.
# --------------------------------------------------------------------------
R9="$TEST_DIR/metadata-reconcile"
setup_repo "$R9"
# Diverge the committed metadata so the regenerated file is a real modification.
perl -0pi -e 's/"loom_version": "[^"]*"/"loom_version": "0.0.0-old"/' \
  "$R9/.loom/install-metadata.json"
git -C "$R9" add .loom/install-metadata.json
git -C "$R9" commit -qm "simulate older install metadata" >/dev/null 2>&1
R9_OUT="$TEST_DIR/metadata-out.txt"
"$INSTALL_SCRIPT" -y --quick "$R9" >"$R9_OUT" 2>&1
META_STATUS="$(git -C "$R9" status --porcelain -- .loom/install-metadata.json)"
if printf '%s\n' "$META_STATUS" | grep -qE '^D '; then
  fail "install-metadata.json left as a staged DELETION after reinstall (#3611)"
elif printf '%s\n' "$META_STATUS" | grep -qE '^\?\?'; then
  fail "install-metadata.json left UNTRACKED (??) after reinstall (#3611)"
else
  pass "install-metadata.json is not D+?? after reinstall (#3611)"
fi
if printf '%s\n' "$META_STATUS" | grep -qE '^.?M'; then
  pass "install-metadata.json shows as a tracked modification after reinstall (#3611)"
else
  fail "install-metadata.json not a tracked modification (status: '$META_STATUS') (#3611)"
fi
if git -C "$R9" ls-files --error-unmatch .loom/install-metadata.json >/dev/null 2>&1; then
  pass "install-metadata.json remains tracked (git ls-files) after reinstall (#3611)"
else
  fail "install-metadata.json dropped from git ls-files after reinstall (#3611)"
fi
if grep -q "Missing critical file: .loom/install-metadata.json" "$R9_OUT"; then
  fail "verify_install reported install-metadata.json missing (#3611)"
else
  pass "verify_install still finds install-metadata.json (#3611)"
fi
echo ""

# --------------------------------------------------------------------------
# Scenario 10 (#3611): sibling / non-Loom STAGED changes remain untouched
# alongside the staged .gitignore restore (no #3597 scoping regression).
# --------------------------------------------------------------------------
R10="$TEST_DIR/sibling-staged-untouched"
setup_repo "$R10"
mkdir -p "$R10/.anvil"
echo "anvil metadata" >"$R10/.anvil/install-metadata.json"
echo "sibling work" >"$R10/sibling.txt"
git -C "$R10" add .anvil/install-metadata.json sibling.txt
echo "sibling-local-dir/" >>"$R10/.gitignore"
git -C "$R10" add .gitignore
"$INSTALL_SCRIPT" -y --quick "$R10" >/dev/null 2>&1
if git -C "$R10" diff --staged --name-only | grep -qxF ".anvil/install-metadata.json" && \
   git -C "$R10" diff --staged --name-only | grep -qxF "sibling.txt"; then
  pass "sibling non-Loom staged changes remain staged (no #3597 regression, #3611)"
else
  fail "sibling non-Loom staged changes were disturbed by reinstall (#3611)"
fi
if [[ "$(cat "$R10/.anvil/install-metadata.json")" == "anvil metadata" ]] && \
   [[ "$(cat "$R10/sibling.txt")" == "sibling work" ]]; then
  pass "sibling non-Loom file contents untouched (#3611)"
else
  fail "sibling non-Loom file contents mutated by reinstall (#3611)"
fi
echo ""

echo "======================================"
echo "Test Summary"
echo "======================================"
echo -e "${GREEN}Passed: $passed${NC}"
echo -e "${RED}Failed: $failed${NC}"
echo ""
if [[ $failed -eq 0 ]]; then
  echo -e "${GREEN}All tests passed!${NC}"
  exit 0
else
  echo -e "${RED}Some tests failed.${NC}"
  exit 1
fi
