name: 'Retry Command'
description: 'Retry a command with configurable attempts and backoff'
author: 'Loom Team'

inputs:
  command:
    description: 'Command to execute'
    required: true
  max_attempts:
    description: 'Maximum number of attempts'
    required: false
    default: '3'
  retry_wait_seconds:
    description: 'Seconds to wait between retries'
    required: false
    default: '5'
  timeout_minutes:
    description: 'Timeout in minutes for each attempt'
    required: false
    default: '10'
  shell:
    description: 'Shell to use for command execution'
    required: false
    default: 'bash'

runs:
  using: 'composite'
  steps:
    - name: Execute command with retry
      shell: ${{ inputs.shell }}
      run: |
        set +e  # Don't exit on error - we handle it

        MAX_ATTEMPTS=${{ inputs.max_attempts }}
        RETRY_WAIT=${{ inputs.retry_wait_seconds }}
        TIMEOUT_MINUTES=${{ inputs.timeout_minutes }}
        TIMEOUT_SECONDS=$((TIMEOUT_MINUTES * 60))
        COMMAND="${{ inputs.command }}"

        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔄 Retry Command Configuration"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Command: $COMMAND"
        echo "Max attempts: $MAX_ATTEMPTS"
        echo "Retry wait: ${RETRY_WAIT}s"
        echo "Timeout per attempt: ${TIMEOUT_MINUTES}m"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""

        attempt=1
        while [ $attempt -le $MAX_ATTEMPTS ]; do
          echo "📍 Attempt $attempt of $MAX_ATTEMPTS"
          echo "⏰ Started at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"

          # Run command with timeout
          if timeout ${TIMEOUT_SECONDS}s bash -c "$COMMAND"; then
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "✅ Command succeeded on attempt $attempt"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            exit 0
          fi

          exit_code=$?
          echo ""

          if [ $exit_code -eq 124 ]; then
            echo "⏱️  Command timed out after ${TIMEOUT_MINUTES} minutes"
          else
            echo "❌ Command failed with exit code: $exit_code"
          fi

          if [ $attempt -lt $MAX_ATTEMPTS ]; then
            echo "⏳ Waiting ${RETRY_WAIT}s before retry..."
            sleep $RETRY_WAIT
            echo ""
          fi

          attempt=$((attempt + 1))
        done

        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "💥 Command failed after $MAX_ATTEMPTS attempts"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        exit 1
