//! Credential-free lifecycle canary for the observability trials (#8527).
//!
//! Drives the real [`lifecycle`] hook and the real `sweep-checkpoint` CLI
//! through one sweep that includes a rejected Judge, a Doctor repair and a
//! successful Judge, drains the journal exactly as the daemon does, then ships
//! the result with the real `telemetry-export` CLI to an operator-supplied
//! neutral collector. Nothing here is hand-built span data: trace and span IDs
//! are generated by the lifecycle code and timestamps are wall-clock
//! observations. It is NOT a model run and NOT a dispatched issue lifecycle —
//! the Judge/Doctor attempts are checkpoint writes, not real role executions
//! (that evidence is #8525's). `expected-spans.json` in the evidence directory
//! is what a backend query must reproduce; see
//! `defaults/observability/clickstack/README.md`.
#![cfg(feature = "otlp")]
#![allow(clippy::unwrap_used, clippy::expect_used)]
use loom_daemon::{
    observability::{lifecycle, queue::DurableQueue},
    telemetry::{
        trace::{SpanName, SpanStatus},
        TelemetryRecord,
    },
};
use serde_json::json;
use std::{io::Write, path::Path, process::Command};

const ISSUE: &str = "8527";
const PR: &str = "8527";

fn required(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| {
        panic!("{name} must be set; see defaults/observability/clickstack/README.md")
    })
}

fn checkpoint(root: &Path, sweep: &lifecycle::Span, phase: &str, attempt: &str) {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_loom-daemon"));
    cmd.current_dir(root)
        .env("LOOM_WORKSPACE", root)
        .env("LOOM_CONFIG_DEFAULTS_FILE", "")
        .env("LOOM_SHARED_API_KEYS_DIR", "")
        .env_remove("LOOM_ROLE")
        .env_remove("LOOM_MODEL")
        .env_remove("LOOM_MODEL_PROFILE")
        .env("LOOM_OBSERVABILITY_ENABLED", "true")
        .env("LOOM_OBSERVABILITY_EXPORTER", "otlp")
        .env("LOOM_OBSERVABILITY_ENDPOINT", "http://127.0.0.1:4318")
        .args([
            "sweep-checkpoint",
            "write",
            ISSUE,
            phase,
            "--pr-number",
            PR,
            "--attempt",
            attempt,
        ]);
    sweep.command(&mut cmd);
    let out = cmd.output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
}

#[test]
#[ignore = "requires a running trial collector; see defaults/observability/clickstack/README.md"]
fn lifecycle_canary_exports_a_repair_waterfall_to_the_trial_collector() {
    let endpoint = required("LOOM_TRIAL_COLLECTOR_ENDPOINT");
    let key_file = required("LOOM_TRIAL_COLLECTOR_KEY_FILE");
    let evidence = std::path::PathBuf::from(required("LOOM_TRIAL_EVIDENCE_DIR"));
    // A new private directory: never overwrite earlier evidence.
    let mut builder = std::fs::DirBuilder::new();
    #[cfg(unix)]
    {
        use std::os::unix::fs::DirBuilderExt;
        builder.mode(0o700);
    }
    builder
        .create(&evidence)
        .expect("LOOM_TRIAL_EVIDENCE_DIR must name a new directory");

    let workspace = tempfile::tempdir().unwrap();
    let root = workspace.path();
    std::fs::create_dir_all(root.join(".loom")).unwrap();
    std::fs::write(
        root.join(".loom/config.json"),
        json!({"observability":{"enabled":true,"exporter":"otlp","endpoint":"http://127.0.0.1:4318"}})
            .to_string(),
    )
    .unwrap();

    let execution = format!("trial-canary-{}", uuid::Uuid::new_v4());
    let sweep = lifecycle::begin(
        root,
        &execution,
        SpanName::Sweep,
        lifecycle::attributes(&[("loom.sweep_id", &execution), ("loom.issue", ISSUE)]),
    )
    .expect("tracing is enabled in this workspace");
    for (phase, attempt) in [
        ("curator-done", "1"),
        ("builder-done", "1"),
        ("judge-rejected", "1"),
        ("doctor-done", "2"),
        ("judge-done", "2"),
        ("merge-done", "2"),
    ] {
        checkpoint(root, &sweep, phase, attempt);
    }
    lifecycle::finish_execution(root, &execution, "success", Default::default());

    let queue = DurableQueue::open(root.join("canary-queue.jsonl"), 1000);
    lifecycle::backfill(root, &queue);
    assert_eq!(queue.dropped_total(), 0);
    let envelopes = queue.peek_batch(1000);
    let spans: Vec<_> = envelopes
        .iter()
        .filter_map(|e| match &e.record {
            TelemetryRecord::Span(span) => Some(span),
            _ => None,
        })
        .collect();
    let trace_id = sweep.context().trace_id.as_str().to_owned();
    assert!(spans.len() >= 13, "root + 6 phases + 6 attempts: {spans:?}");
    assert!(spans
        .iter()
        .all(|s| s.context.trace_id.as_str() == trace_id));
    let judges: Vec<_> = spans
        .iter()
        .filter(|s| s.name == SpanName::RoleAttempt && s.attributes["loom.role"] == "judge")
        .collect();
    assert_eq!(judges.len(), 2);
    assert!(judges.iter().any(|s| s.status == SpanStatus::Error));
    assert!(judges.iter().any(|s| s.status == SpanStatus::Ok));

    let path = evidence.join("envelopes.jsonl");
    let mut file = std::fs::File::create(&path).unwrap();
    for envelope in &envelopes {
        serde_json::to_writer(&mut file, envelope).unwrap();
        file.write_all(b"\n").unwrap();
    }
    file.sync_all().unwrap();
    let expected: Vec<_> = spans
        .iter()
        .map(|s| {
            json!({
                "trace_id": s.context.trace_id.as_str(),
                "span_id": s.context.span_id.as_str(),
                "parent_span_id": s.parent_span_id.as_ref().map(|p| p.as_str()),
                "name": s.name.as_str(),
                "role": s.attributes.get("loom.role"),
                "status": s.status,
                "started_unix_nano": s.started_at.timestamp_nanos_opt(),
                "ended_unix_nano": s.ended_at.timestamp_nanos_opt(),
            })
        })
        .collect();
    let report = json!({"trace_id": trace_id, "execution_id": execution, "spans": expected});
    std::fs::write(
        evidence.join("expected-spans.json"),
        serde_json::to_vec_pretty(&report).unwrap(),
    )
    .unwrap();

    let out = Command::new(env!("CARGO_BIN_EXE_loom-daemon"))
        .args(["telemetry-export", "--input"])
        .arg(&path)
        .args(["--endpoint", &endpoint, "--key-file", &key_file])
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "collector did not acknowledge the canary: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    println!("{}", json!({"trace_id": trace_id, "spans": spans.len(), "evidence": evidence}));
}
