//! Differential test: the ported `extract-refs` against a frozen oracle of the
//! **pre-port shell's** answers (epic #7810, filed from #8072; corpus gaps
//! closed by #8097).
//!
//! # Why this exists
//!
//! The port method for epic #7810 is "keep the shell's test suite and run its
//! assertions unchanged against the Rust" — a retained black-box suite as the
//! equivalence proof. #8011 showed the limit of that method: the `dep_recheck`
//! port shipped **three** silent behavioural divergences while its retained
//! suite was 104/104 green. A retained suite proves only what its author
//! thought to write down, and nobody writes down the input they did not
//! imagine. All three escapees were inputs nobody imagined.
//!
//! Differential testing closes exactly that gap, because the corpus is
//! *generated* from the grammar the implementation parses rather than
//! hand-picked. This test replays every case in
//! `fixtures/extract_refs_shell_oracle.jsonl` (regenerated by
//! `examples/generate_extract_refs_oracle.rs`; see its own `_meta.corpus` for
//! the current count and coverage) and asserts the port differs from the
//! shell in only the ways we have deliberately accepted.
//!
//! # Why an oracle file rather than running the shell
//!
//! The pre-port shell is gone from the tree (that was the point). Running it
//! here would mean either a `git show` against a pinned rev — which breaks
//! under CI's default shallow checkout — or vendoring 821 lines of dead shell
//! plus a runtime `bash` **and** `jq` dependency into `cargo test`. Instead the
//! shell's answers are frozen into a fixture once, by the documented command in
//! its `_meta` record, and this test needs no shell at all.
//!
//! # What a failure here means
//!
//! `UNEXPLAINED` means the port now differs from the retired shell in a way
//! nobody has classified. That is the #8011 shape recurring: read the reported
//! case, decide whether the new behaviour is right, then either fix it or add
//! the class here **with** its reasoning. Do not silence it by widening a class.
//!
//! The per-class counts are a characterization, not a contract — they change
//! when `extract()` legitimately changes. The zero-`UNEXPLAINED` assertion is
//! the real invariant.
//!
//! # Each class is recognised by its mechanism
//!
//! Review caught the first version of this test recognising the newline class as
//! "the port found an extra reference and the body contains a newline". That is
//! a property of the INPUT, and 88% of these bodies contain a newline, so the
//! class absorbed an extra reference from any cause — measured against the
//! case-insensitivity mutation below, it caught 9 of the 116 cases the mutation
//! actually changed. [`newline_only_refs`] now computes what the class can
//! genuinely produce, and the extras must be a subset of exactly that: same
//! green baseline, 116 of 116 caught.
//!
//! A class whose test is a property of the input is a hole shaped like a class.

use loom_daemon::dep_recheck::extract::{comment_counts, extract, Comment, Input};

/// Frozen answers from the pre-port shell. See the `_meta` first line.
const ORACLE: &str = include_str!("fixtures/extract_refs_shell_oracle.jsonl");

/// The bot login the oracle was generated with. Must match `_meta.bot_login`.
const BOT_LOGIN: &str = "loom-bot";

/// The three accepted ways the port differs from the shell it replaced.
#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
enum Divergence {
    /// The shell matched with `grep -oE`, which is line-oriented and cannot
    /// span a newline; the Rust regex runs over the whole text with
    /// `[[:space:]]` inside `[*_:[[:space:]]]*` matching `\n`. So
    /// `"Blocked by\n#42"` matches here and did not there. Documented and
    /// kept in `extract.rs` (#8011): missing a genuine declared reference is
    /// the worse failure for a check whose whole job is finding one.
    NewlineSpan,
    /// `#007`. The shell's `sort -un` sorts numerically but prints the ORIGINAL
    /// token, so it emitted `007`; the Rust parses to `u64` and prints `7`.
    /// Both denote issue 7, and GitHub resolves `#007` to issue 7, so the Rust
    /// spelling is the more correct one — but it does change `CONCLUSION_HASH`
    /// for any text using a zero-padded reference.
    LeadingZero,
    /// A `#N` above `u64::MAX` (boundary confirmed exactly at
    /// 18446744073709551615 vs ...616). `extract()` drops it via
    /// `.parse().ok()`; the shell kept the literal token. No real issue number
    /// is 20 digits, so this is reachable only from adversarial forge text.
    /// Downstream a dropped ref is usually fail-SAFE (zero refs yields
    /// `verdict: open`, i.e. still blocked), but in a MIXED set — one merged
    /// ref plus one dropped — the verdict becomes `stale-premise` where the
    /// shell would instead have hard-errored on the unfetchable token.
    OverflowDropped,
}

/// One frozen case. `comments` were added in #8097 — earlier versions of this
/// fixture ran every case with `comments: []`, leaving `comment_counts`,
/// `normalise_login`, and the `OWN_MARKERS` filter entirely untested by this
/// differential harness, and making the `bot_login` assertion in
/// [`load_oracle`] inert (re-running with a different bot login produced
/// byte-identical output). It no longer is: several corpus cases now carry a
/// comment whose inclusion depends on matching `BOT_LOGIN` exactly.
struct Case {
    body: String,
    comments: Vec<Comment>,
    shell_refs: String,
}

fn load_oracle() -> Vec<Case> {
    let mut cases = Vec::new();
    for (i, line) in ORACLE.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let v: serde_json::Value =
            serde_json::from_str(line).unwrap_or_else(|e| panic!("oracle line {}: {e}", i + 1));
        if v.get("_meta").is_some() {
            // Provenance record; assert it still describes this test's setup.
            let meta = &v["_meta"];
            assert_eq!(
                meta["bot_login"].as_str(),
                Some(BOT_LOGIN),
                "oracle was generated with a different --bot-login than this test uses"
            );
            continue;
        }
        let comments: Vec<Comment> = match v.get("comments") {
            Some(c) => serde_json::from_value(c.clone())
                .unwrap_or_else(|e| panic!("oracle line {}: comments: {e}", i + 1)),
            None => Vec::new(),
        };
        cases.push(Case {
            body: v["body"].as_str().expect("body").to_string(),
            comments,
            shell_refs: v["shell_refs"].as_str().expect("shell_refs").to_string(),
        });
    }
    cases
}

/// The text `extract()` actually scans for a case: the body, plus every
/// comment `comment_counts` keeps, each preceded by a `\n` — mirroring
/// `extract()`'s own assembly step exactly (via the same `comment_counts`
/// the port calls) rather than re-deriving the inclusion rule here and
/// risking it drifting out of sync.
fn effective_text(case: &Case, bot_login: &str) -> String {
    let mut text = case.body.clone();
    for c in &case.comments {
        if comment_counts(c, bot_login) {
            text.push('\n');
            text.push_str(&c.body);
        }
    }
    text
}

/// References the phrase pattern finds over the WHOLE text but not within any
/// single line — exactly what the accepted newline-spanning divergence can
/// account for, and nothing else.
///
/// The shell matched with `grep -oE`, which is line-oriented and cannot span
/// a newline; the port's regex runs over the concatenated text with
/// `[[:space:]]` (inside `[*_:[[:space:]]]*`) matching `\n`. Deliberately the
/// SAME character class `extract.rs`'s `phrase_re` uses post-#8097 (not the
/// Unicode-aware `\s` this helper used before it) — NBSP no longer widens
/// this class on either side, so a case whose only separator is NBSP simply
/// finds nothing on both sides rather than landing here. Normalised through
/// `u64` the way the port does, so a zero-padded token compares equal to its
/// canonical form.
fn newline_only_refs(text: &str) -> std::collections::BTreeSet<String> {
    static RE: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
    let re = RE.get_or_init(|| {
        regex::Regex::new(
            r"(Blocked by|Depends on|Requires|\*\*Epic\*\*)[*_:[[:space:]]]*#([0-9]+)",
        )
        .expect("static dependency-phrase pattern")
    });
    let nums = |t: &str| -> std::collections::BTreeSet<String> {
        re.captures_iter(t)
            .filter_map(|c| c.get(2)?.as_str().parse::<u64>().ok())
            .map(|n| n.to_string())
            .collect()
    };
    let whole = nums(text);
    let per_line: std::collections::BTreeSet<String> = text.lines().flat_map(nums).collect();
    whole.difference(&per_line).cloned().collect()
}

/// Explain every token-level difference between the shell's answer and the
/// port's, or return `Err` describing the part that no known class covers.
///
/// `text` must be the FULL text `extract()` scanned for this case — body plus
/// every comment `comment_counts` kept — not just the body; see
/// [`effective_text`]. Comment-bearing cases (#8097) can span a
/// newline-spanning divergence at the body/comment join, which a body-only
/// view of the text cannot see.
fn classify(text: &str, shell: &str, rust: &str) -> Result<Vec<Divergence>, String> {
    let mut classes = Vec::new();

    // Re-derive what the shell's tokens become under the port's own rules:
    // parse as u64, dropping anything that overflows.
    let mut normalised: Vec<String> = Vec::new();
    for tok in shell.split_whitespace() {
        match tok.parse::<u64>() {
            Ok(v) => {
                if tok != v.to_string() {
                    classes.push(Divergence::LeadingZero);
                }
                normalised.push(v.to_string());
            }
            Err(_) => classes.push(Divergence::OverflowDropped),
        }
    }
    normalised.sort_unstable_by_key(|s| s.parse::<u64>().unwrap_or(u64::MAX));
    normalised.dedup();

    let got: Vec<&str> = rust.split_whitespace().collect();

    let extra: Vec<String> = got
        .iter()
        .filter(|t| !normalised.contains(&t.to_string()))
        .map(|t| (*t).to_string())
        .collect();
    if !extra.is_empty() {
        // Recognise the class by its MECHANISM, not by a property of the input
        // that merely correlates with it. Keying this on `body.contains('\n')`
        // absorbed an extra ref from ANY cause, because 88% of these bodies
        // contain a newline — so a later change that stopped dropping overflow
        // refs, say, would have slipped through silently. Compute instead what
        // the newline divergence can actually produce, and require the extras
        // to be a subset of exactly that.
        let explainable = newline_only_refs(text);
        let unexplained: Vec<&String> =
            extra.iter().filter(|t| !explainable.contains(*t)).collect();
        if unexplained.is_empty() {
            classes.push(Divergence::NewlineSpan);
        } else {
            return Err(format!(
                "port reported {unexplained:?} which the shell did not, and the \
                 newline-spanning divergence cannot produce them: the pattern does not match \
                 them across a line break in this input either"
            ));
        }
    }

    let missing: Vec<&String> = normalised
        .iter()
        .filter(|t| !got.contains(&t.as_str()))
        .collect();
    if !missing.is_empty() {
        return Err(format!(
            "port DROPPED {missing:?}, which the shell found and which parse cleanly as u64 — \
             no accepted class explains losing a declared reference"
        ));
    }

    // Same reference SET, different string. None of the three accepted classes
    // is about rendering, so ordering/separator/formatting drift must not be
    // absorbed by a LeadingZero or OverflowDropped class that merely happened
    // to apply to this input.
    if extra.is_empty() && missing.is_empty() {
        let want = normalised.join(" ");
        if rust != want {
            return Err(format!(
                "port and shell agree on WHICH references were found but render them \
                 differently: expected {want:?}, got {rust:?} — no accepted class is about \
                 ordering or formatting"
            ));
        }
    }

    classes.sort_unstable_by_key(|c| format!("{c:?}"));
    classes.dedup();
    Ok(classes)
}

#[test]
fn ported_extract_refs_diverges_from_the_retired_shell_only_in_known_ways() {
    let cases = load_oracle();
    assert!(
        cases.len() >= 750,
        "oracle shrank to {} cases — a differential test that runs almost nothing passes for \
         the wrong reason",
        cases.len()
    );
    let comment_bearing = cases.iter().filter(|c| !c.comments.is_empty()).count();
    assert!(
        comment_bearing >= 50,
        "oracle has only {comment_bearing} comment-bearing cases — #8097 exists because every \
         case used to run with comments: [], leaving comment_counts/normalise_login/OWN_MARKERS \
         untested by this differential harness; a near-empty count would recreate that gap",
    );

    let mut agreed = 0usize;
    let mut per_class = std::collections::BTreeMap::<String, usize>::new();
    let mut unexplained = Vec::new();

    for case in &cases {
        let input = Input {
            body: case.body.clone(),
            comments: case.comments.clone(),
        };
        let rust = extract(&input, BOT_LOGIN);

        if rust == case.shell_refs {
            agreed += 1;
            continue;
        }
        let text = effective_text(case, BOT_LOGIN);
        match classify(&text, &case.shell_refs, &rust) {
            Ok(classes) if classes.is_empty() => unexplained.push(format!(
                "body={:?}\n    shell=[{}]  port=[{}]\n    outputs differ but no class applies",
                case.body, case.shell_refs, rust
            )),
            Ok(classes) => {
                for c in classes {
                    *per_class.entry(format!("{c:?}")).or_default() += 1;
                }
            }
            Err(why) => unexplained.push(format!(
                "body={:?}\n    shell=[{}]  port=[{}]\n    {why}",
                case.body, case.shell_refs, rust
            )),
        }
    }

    assert!(
        unexplained.is_empty(),
        "{} of {} generated inputs diverge from the retired shell in UNCLASSIFIED ways.\n\
         This is the #8011 shape: a divergence that a retained black-box suite would not \
         have noticed.\n\n{}",
        unexplained.len(),
        cases.len(),
        unexplained
            .iter()
            .take(10)
            .map(|s| format!("  - {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    // Characterization. Update deliberately when `extract()` changes; a shift
    // here is a real behaviour change and should be explained in the commit.
    // Re-baselined in #8097: the corpus grew from 700 body-only cases
    // covering only space/newline to 798 cases covering the full 7-member
    // separator alphabet plus comment-bearing inputs, AND `phrase_re`
    // narrowed its separator class from Unicode `\s` to the ASCII
    // `[[:space:]]` POSIX class (dropping NBSP) — so both the corpus and
    // `extract()` changed together here; these counts characterize the
    // result of both, not a corpus-only shift.
    assert_eq!(agreed, 463, "cases where the port and the shell agree exactly");
    assert_eq!(per_class.get("NewlineSpan").copied().unwrap_or(0), 77);
    assert_eq!(per_class.get("LeadingZero").copied().unwrap_or(0), 128);
    assert_eq!(per_class.get("OverflowDropped").copied().unwrap_or(0), 130);
}
