name: Performance Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    name: Rust Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build benchmarks
        run: cargo bench --workspace --no-run

      - name: Run benchmarks
        run: cargo bench --workspace --no-fail-fast
