name: Check defaults/ and .loom/ sync

on:
  pull_request:
    paths:
      - 'defaults/**'
      - '.loom/**'
  push:
    branches:
      - main
    paths:
      - 'defaults/**'
      - '.loom/**'

jobs:
  check-sync:
    name: Verify defaults/ matches .loom/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check script files match
        run: |
          echo "Checking scripts..."
          MISMATCH=0

          for file in defaults/scripts/*.sh; do
            basename=$(basename "$file")
            loom_file=".loom/scripts/$basename"

            if [ -f "$loom_file" ]; then
              if ! diff -q "$file" "$loom_file" > /dev/null 2>&1; then
                echo "❌ MISMATCH: $basename"
                echo "Differences:"
                diff -u "$file" "$loom_file" || true
                MISMATCH=1
              else
                echo "✓ OK: $basename"
              fi
            else
              echo "⚠️  WARNING: $loom_file does not exist"
            fi
          done

          if [ $MISMATCH -eq 1 ]; then
            echo ""
            echo "ERROR: Files in defaults/scripts/ do not match .loom/scripts/"
            echo "Please ensure both directories are in sync."
            exit 1
          fi

      - name: Check role markdown files match
        run: |
          echo "Checking role markdown files..."
          MISMATCH=0

          for file in defaults/roles/*.md; do
            basename=$(basename "$file")
            loom_file=".loom/roles/$basename"

            if [ -f "$loom_file" ]; then
              if ! diff -q "$file" "$loom_file" > /dev/null 2>&1; then
                echo "❌ MISMATCH: $basename"
                echo "Differences:"
                diff -u "$file" "$loom_file" || true
                MISMATCH=1
              else
                echo "✓ OK: $basename"
              fi
            else
              echo "⚠️  WARNING: $loom_file does not exist"
            fi
          done

          if [ $MISMATCH -eq 1 ]; then
            echo ""
            echo "ERROR: Files in defaults/roles/ do not match .loom/roles/"
            echo "Please ensure both directories are in sync."
            exit 1
          fi

      - name: Check role JSON files match
        run: |
          echo "Checking role JSON files..."
          MISMATCH=0

          for file in defaults/roles/*.json; do
            basename=$(basename "$file")
            loom_file=".loom/roles/$basename"

            if [ -f "$loom_file" ]; then
              if ! diff -q "$file" "$loom_file" > /dev/null 2>&1; then
                echo "❌ MISMATCH: $basename"
                echo "Differences:"
                diff -u "$file" "$loom_file" || true
                MISMATCH=1
              else
                echo "✓ OK: $basename"
              fi
            else
              echo "⚠️  WARNING: $loom_file does not exist"
            fi
          done

          if [ $MISMATCH -eq 1 ]; then
            echo ""
            echo "ERROR: Files in defaults/roles/ do not match .loom/roles/"
            echo "Please ensure both directories are in sync."
            exit 1
          fi

      - name: Summary
        if: success()
        run: |
          echo ""
          echo "✅ All files in defaults/ match .loom/"
          echo "The installation templates are in sync."
