name: Label external issues

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  label_external:
    runs-on: ubuntu-latest
    steps:
      - name: Check if author is a collaborator
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const username = context.payload.issue.user.login;

            try {
              await github.rest.repos.checkCollaborator({
                owner,
                repo,
                username
              });
              console.log(`${username} is a collaborator`);
              return { isCollaborator: true };
            } catch (error) {
              console.log(`${username} is NOT a collaborator`);
              return { isCollaborator: false };
            }

      - name: Add 'external' label if not a collaborator
        if: fromJSON(steps.check.outputs.result).isCollaborator == false
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['external']
            });

      - name: Post welcome comment on external issues
        if: fromJSON(steps.check.outputs.result).isCollaborator == false
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Thank you for your feedback! 🙏

This issue has been labeled as \`external\` and will be reviewed by the maintainers. Our AI agents are instructed to ignore external issues to focus on the internal development workflow.

For more information about contributing to Loom, see [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md).`
            });
